### ISSUE TITLE
Return value expected on def f() -> Optional[Type]: with plain return

### ISSUE THREAD

**Issue by darjus** [JukkaL/mypy#1003]
mypy is expecting me to explicitly `return None` instead of `return`, but I'd expect that to be inferred as there's little point in me telling it i return None

    def f(i: int) -> Optional[int]:
        if i > 3:
            return  # fails but return None works
        return i * 3

**Comment by gvanrossum** [comment]
Actually this is intentional -- it's a code smell and even called out in PEP 8 (https://www.python.org/dev/peps/pep-0008/#programming-recommendations, "Be consistent in return statements.")

**Comment by darjus** [comment]
Thanks for explaining this @gvanrossum . I've read pep8 several times before but didn't quite follow this specific recommendation, moreover pep8 command does not complain (at least my version) about this.
The actual message is `error: Return value expected` which threw me off.
Should we invest in a more descriptive message and or documentation (I'm willing to submit a pr for this), or you think this is sufficient?

**Comment by gvanrossum** [comment]
Sadly the pep8 tool's name is an insult to the intentions of the PEP 8
document.

**Comment by mlissner** [comment]
I'm all for eliminating code smells, but I just struggled with this error a bit because I'm not in the state of mind to fix pep8 stuff when I run mypy. 

I'd suggest removing this warning since it isn't about typing. If the function returns None and that's what the signature calls for, then mypy shouldn't complain otherwise.

**Comment by acushner-rippling** [comment]
@mlissner couldn't agree with you more. mypy should stay in its type-checking lane and leave style to something else.
