### ISSUE TITLE
Implement type-checking dict-used-as-record

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#1012]
Some code uses dicts with a fixed set of keys a lot as a poor-man's struct or record type. If the value types are heterogeneous this is hard to type-check, as code often assumes a given type for a given key. (Namedtuple doesn't really replace this, since it's immutable.)

This is a placeholder issue so I can refer to it -- Jukka has a bit of a design in his head already.

**Comment by gnprice** [comment]
I think this is #985.
