### ISSUE TITLE
Why a custom parser ?

### ISSUE THREAD

**Issue by raph-amiard** [JukkaL/mypy#1014]
This is more a question than an issue. While browsing the code of mypy to figure out how to contribute, and what to contribute, I stumbled upon the fact that it seems to have its own complete python parser.

While python is admittedly not a terribly complicated language to parse, I was wondering about why does it have a custom parser, since it uses regular python syntax (except maybe in python2 mode).

Is it a legacy thing ? or is there a stronger rationale behind this ?

Sorry if this is a redundant question, couldn't find any reference to that in the docs/issue tracker.

Regards,

**Comment by gvanrossum** [comment]
It's part legacy (mypy was originally intended to be a different language), but also the "standard" parser in Python doesn't return comments, which would make interpreting `# type: ...` comments really hard.

**Comment by raph-amiard** [comment]
Ok, makes sense, thanks :)
