### ISSUE TITLE
Type checks applied only on global scope?

### ISSUE THREAD

**Issue by ttsiodras** [JukkaL/mypy#1018]
Just started testing the waters with mypy. 
In this first test I did, it appears that mypy catches the type errors at global scope, but not when they occur in function scope. Here's the test case:

    $ cat common.py
    import typing
    import itertools, math
    from typing import Iterator
    
    # I deliberately add an unused str param to test the typechecking...
    def primeSpiralPixels(s: str) -> Iterator[int]:
        yield 255  # 1 is not prime (white)
        yield 0    # 2 is prime     (black)
        primesSoFar = [2]
        for candidate in itertools.count(3):
            for prime in (
                    p for p in primesSoFar if p <= int(math.sqrt(candidate))):
                if 0 == candidate % prime:
                    yield 255  # non-prime: white
                    break
            else:
                primesSoFar.append(candidate)
                yield 0  # prime: black

    $ cat test.py
    #!/usr/bin/env python3
    import typing
    
    from common import primeSpiralPixels
    
    print("Ole")
    print(primeSpiralPixels(dict()))
    print("asda" + primeSpiralPixels("foo"))
    
    #def main():
    #    print("Ole")
    #    print(primeSpiralPixels(dict()))
    #    print("asda" + primeSpiralPixels("foo"))
    #if __name__ == "__main__":
    #    main()
    
This works:

    $ mypy test.py
    test.py:6: error: Argument 1 to "primeSpiralPixels" has incompatible type Dict[None, None]; expected "str"
    test.py:7: error: Unsupported operand types for + ("str" and Iterator[int])
    
But when I uncomment the `main` function...

    $ cat test.py
    #!/usr/bin/env python3
    import typing
    
    from common import primeSpiralPixels
    
    def main():
        print("Ole")
        print(primeSpiralPixels(dict()))
        print("asda" + primeSpiralPixels("foo"))
    
    if __name__ == "__main__":
        main()

I get no errors with this:

    $ mypy test.py
    $ 

Why?

**Comment by ttsiodras** [comment]
My bad, I had a .pyi file laying around. Sorry for the noise!

**Comment by gvanrossum** [comment]
Why reopen?

**Comment by ttsiodras** [comment]
Sorry Guido - I just realized I can reproduce it without the .pyi stub file.

**Comment by gvanrossum** [comment]
It won't check the code in main() unless you add an annotation to it -- in this case use
```
def main() -> None:
```

**Comment by ttsiodras** [comment]
Thanks, much appreciated!
