### ISSUE TITLE
Calling class that inherits __init__ from an Any base class

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#1049]
Consider this code:

```
from typing import Any
A = None # type: Any
class B(A): pass
B(1)  # Too many arguments for "B"
```

Mypy complains about `B(1)` even though we should implicitly treat `B` as having signature `(*Any, **Any)` since there is an unknown base class `A` and `B` doesn't override `__init__` or `__new__`.

**Comment by kootenpv** [comment]
Note that you'd actually get:

```
    class B(A):
TypeError: NoneType takes no arguments
```

**Comment by gvanrossum** [comment]
That's okay. Code involving `Any` isn't type-checked by mypy, and can have any behavior at runtime depending on what's actually happening.
