### ISSUE TITLE
Code review policy

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#1070]
I propose the following policy for code review, to unload Jukka a bit: either one of Jukka, Greg and Guido can merge PRs by others if they feel confident. (@JukkaL: you may have to add @gnprice to the project.) Jukka (being the BDFL) can commit whatever he wants but is free to request reviews.

(This came up in a comment on https://github.com/JukkaL/mypy/pull/1066#issuecomment-164002155)

**Comment by gnprice** [comment]
+1

**Comment by JukkaL** [comment]
Sound good -- let's do this! I guess we don't need anything more official than this and I can close the issue?

**Comment by gvanrossum** [comment]
Yup.

--Guido (mobile)
