### ISSUE TITLE
internal error using Enum and __new__

### ISSUE THREAD

**Issue by bcdarwin** [JukkaL/mypy#1081]
Making a list of types looks weird, but this was originally used to construct a `typing.NamedTuple`.

```
import typing
from typing import Tuple, Callable, Any, List
from enum import Enum

class MyEnum(Enum):
    def __new__(cls): pass

def F(fields: List[Callable[[Any], Any]]): pass

class SomeEnum(MyEnum):
    x = 1

F([SomeEnum])
```

produces:

```
Traceback (most recent call last):
  ...
  File "/home/bdarwin/.local/lib/python3.5/site-packages/mypy/types.py", line 346, in accept
    return visitor.visit_callable_type(self)
  File "/home/bdarwin/.local/lib/python3.5/site-packages/mypy/constraints.py", line 231, in visit_callable_type
    template.arg_types[i], cactual.arg_types[i],
IndexError: list index out of range

*** INTERNAL ERROR ***

foo.py:13: error: Internal error -- please report a bug at https://github.com/JukkaL/mypy/issues
The program exited via sys.exit(). Exit status: 1
```

**Comment by gvanrossum** [comment]
Thanks for the report! We've seen a few more of these. Hopefully we'll be
able to nail this, but most of mypy's active developers are about to go on
holiday break so it may be January. Sorry!

**Comment by gvanrossum** [comment]
I've removed a few red herrings from the repro; here's the smallest one I could find:
```
from typing import Any, Callable, List
def f(fields: List[Callable[[Any], Any]]): pass
class C: pass
f([C])
```
Some things I tried that went too far:

- The argument type for f must be a List type
- The Callable type must have an argument

The class's `__init__` signature (here inherited from object) must not match the Callable given.

**Comment by gvanrossum** [comment]
I think I've got a fix -- let me know if that solves your real-world case (I've already verified it solves the repro given here).

**Comment by bcdarwin** [comment]
Yeah, that fixes it.  Thanks!
