### ISSUE TITLE
internal error on setting a value in a dictionary

### ISSUE THREAD

**Issue by dashea** [JukkaL/mypy#1082]
I hit an internal error running on https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/iutil.py, the problem code is:

```
_child_env = {}
def setenv(name, value):
    _child_env[name] = value
```

Here's the traceback:

```
Traceback (most recent call last):
  File "/usr/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/lib/python3.5/site-packages/mypy/main.py", line 50, in main
    type_check_only(sources, bin_dir, options)
  File "/usr/lib/python3.5/site-packages/mypy/main.py", line 93, in type_check_only
    python_path=options.python_path)
  File "/usr/lib/python3.5/site-packages/mypy/build.py", line 203, in build
    result = manager.process(initial_states)
  File "/usr/lib/python3.5/site-packages/mypy/build.py", line 385, in process
    next.process()
  File "/usr/lib/python3.5/site-packages/mypy/build.py", line 882, in process
    self.type_checker().visit_file(self.tree, self.tree.path)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 385, in visit_file
    self.accept(d)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/lib/python3.5/site-packages/mypy/nodes.py", line 381, in accept
    return visitor.visit_func_def(self)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 449, in visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 484, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 567, in check_func_def
    self.accept_in_frame(item.body)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 409, in accept_in_frame
    answer = self.accept(node, type_context)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/lib/python3.5/site-packages/mypy/nodes.py", line 525, in accept
    return visitor.visit_block(self)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 984, in visit_block
    self.accept(s)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/lib/python3.5/site-packages/mypy/nodes.py", line 563, in accept
    return visitor.visit_assignment_stmt(self)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 993, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 1018, in check_assignment
    self.check_indexed_assignment(index_lvalue, rvalue, rvalue)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 1349, in check_indexed_assignment
    basetype = self.accept(lvalue.base)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 396, in accept
    report_internal_error(err, self.errors.file, node.line)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/lib/python3.5/site-packages/mypy/nodes.py", line 922, in accept
    return visitor.visit_name_expr(self)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 1838, in visit_name_expr
    return self.expr_checker.visit_name_expr(e)
  File "/usr/lib/python3.5/site-packages/mypy/checkexpr.py", line 67, in visit_name_expr
    result = self.analyze_ref_expr(e)
  File "/usr/lib/python3.5/site-packages/mypy/checkexpr.py", line 78, in analyze_ref_expr
    context = partial_types[node]
KeyError: <mypy.nodes.Var object at 0x7f8377835240>

*** INTERNAL ERROR ***
```

**Comment by gvanrossum** [comment]
If you run the latest version from the repo (ignore PyPI, it's ancient)
this should print the file and line where it went wrong. It might also be
fixed. Let us know how it goes.

On Sat, Dec 19, 2015 at 6:40 AM, David Shea <notifications@github.com>
wrote:

> I hit an internal error running on
> https://githubcom/rhinstaller/anaconda/blob/master/pyanaconda/iutilpy,
> the problem code is:
>
> _child_env = {}
> def setenv(name, value):
>     _child_env[name] = value
>
> Here's the traceback:
>
> Traceback (most recent call last):
>   File "/usr/bin/mypy", line 6, in <module>
>     main(__file__)
>   File "/usr/lib/python35/site-packages/mypy/mainpy", line 50, in main
>     type_check_only(sources, bin_dir, options)
>   File "/usr/lib/python35/site-packages/mypy/mainpy", line 93, in type_check_only
>     python_path=optionspython_path)
>   File "/usr/lib/python35/site-packages/mypy/buildpy", line 203, in build
>     result = managerprocess(initial_states)
>   File "/usr/lib/python35/site-packages/mypy/buildpy", line 385, in process
>     nextprocess()
>   File "/usr/lib/python35/site-packages/mypy/buildpy", line 882, in process
>     selftype_checker()visit_file(selftree, selftreepath)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 385, in visit_file
>     selfaccept(d)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 394, in accept
>     typ = nodeaccept(self)
>   File "/usr/lib/python35/site-packages/mypy/nodespy", line 381, in accept
>     return visitorvisit_func_def(self)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 449, in visit_func_def
>     selfcheck_func_item(defn, name=defnname())
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 484, in check_func_item
>     selfcheck_func_def(defn, typ, name)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 567, in check_func_def
>     selfaccept_in_frame(itembody)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 409, in accept_in_frame
>     answer = selfaccept(node, type_context)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 394, in accept
>     typ = nodeaccept(self)
>   File "/usr/lib/python35/site-packages/mypy/nodespy", line 525, in accept
>     return visitorvisit_block(self)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 984, in visit_block
>     selfaccept(s)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 394, in accept
>     typ = nodeaccept(self)
>   File "/usr/lib/python35/site-packages/mypy/nodespy", line 563, in accept
>     return visitorvisit_assignment_stmt(self)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 993, in visit_assignment_stmt
>     selfcheck_assignment(slvalues[-1], srvalue, stype is None)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 1018, in check_assignment
>     selfcheck_indexed_assignment(index_lvalue, rvalue, rvalue)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 1349, in check_indexed_assignment
>     basetype = selfaccept(lvaluebase)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 396, in accept
>     report_internal_error(err, selferrorsfile, nodeline)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 394, in accept
>     typ = nodeaccept(self)
>   File "/usr/lib/python35/site-packages/mypy/nodespy", line 922, in accept
>     return visitorvisit_name_expr(self)
>   File "/usr/lib/python35/site-packages/mypy/checkerpy", line 1838, in visit_name_expr
>     return selfexpr_checkervisit_name_expr(e)
>   File "/usr/lib/python35/site-packages/mypy/checkexprpy", line 67, in visit_name_expr
>     result = selfanalyze_ref_expr(e)
>   File "/usr/lib/python35/site-packages/mypy/checkexprpy", line 78, in analyze_ref_expr
>     context = partial_types[node]
> KeyError: <mypynodesVar object at 0x7f8377835240>
>
> *** INTERNAL ERROR ***
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JukkaL/mypy/issues/1082>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by dashea** [comment]
This was with the latest from the repo, I just left off the file name since the three line thing reproduces it. Running on that gives:

```
tmp.py:3: error: Internal error -- please report a bug at https://github.com/JukkaL/mypy/issues
```

as the last line.

**Comment by gvanrossum** [comment]
This looks like a fix -- can you try it in your real-world case?
```
--- a/mypy/checkexpr.py
+++ b/mypy/checkexpr.py
@@ -74,9 +74,11 @@ class ExpressionChecker:
             # Variable reference.
             result = self.analyze_var_ref(node, e)
             if isinstance(result, PartialType):
-                partial_types = self.chk.partial_types[-1]
-                context = partial_types[node]
-                self.msg.fail(messages.NEED_ANNOTATION_FOR_VAR, context)
+                for partial_types in reversed(self.chk.partial_types):
+                    if node in partial_types:
+                        context = partial_types[node]
+                        self.msg.fail(messages.NEED_ANNOTATION_FOR_VAR,
context)
+                        break
                 result = AnyType()
         elif isinstance(node, FuncDef):
             # Reference to a global function.
```
(Sorry, gotta run.)

On Sat, Dec 19, 2015 at 11:08 AM, David Shea <notifications@github.com>
wrote:

> This was with the latest from the repo, I just left off the file name
> since the three line thing reproduces it. Running on that gives:
>
> tmp.py:3: error: Internal error -- please report a bug at https://github.com/JukkaL/mypy/issues
>
> as the last line.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JukkaL/mypy/issues/1082#issuecomment-166016756>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by dashea** [comment]
Looks like it works. Now I get error messages about the dictionary variable needing a type annotation. Thanks!

**Comment by gvanrossum** [comment]
My PR is simpler -- instead of walking down the contexts it just suppresses
the error if the variable isn't in the current scope. I'm not 100% sure
whether that's better or not.

On Sat, Dec 19, 2015 at 2:17 PM, David Shea <notifications@github.com>
wrote:

> Looks like it works. Now I get error messages about the dictionary
> variable needing a type annotation. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JukkaL/mypy/issues/1082#issuecomment-166030565>.
>



-- 
--Guido van Rossum (python.org/~guido)
