### ISSUE TITLE
How can the stub for functools.partial be made to work?

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#1104]
The 2.7 stub for functools contains this elaborate definition for `functools.partial`:
```python
class partial(Generic[_T]):
    func = ...  # Callable[..., _T]
    args = ...  # type: Tuple[Any, ...]
    keywords = ...  # type: Dict[str, Any]
    def __init__(self, func: Callable[..., _T], *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> _T: ...
```
However, despite the presence of a `__call__` method, this isn't compatible with Callable -- e.g. this gives an error:
```python
from typing import *
from functools import partial
def foo(a: int) -> int:
    return a
bar = partial(foo, 42)  # type: Callable[[], int]
```
The error is on the last line:
```
t.py:5: error: Incompatible types in assignment (expression has type partial[int], variable has type Callable[[], int])
```
I can shut it up with a cast but that's ugly. I'd like the checker to at least understand that class partial as given is callable.

**Comment by JukkaL** [comment]
The reason for this is that mypy doesn't consider `partial` to be a subtype of `Callable`, even though it obviously should be. This is a bug in mypy, and there already is an open issue for this: https://github.com/JukkaL/mypy/issues/797

**Comment by gvanrossum** [comment]
Duplicate of #797.
