### ISSUE TITLE
collections.deque is not recognised as MutableSequence

### ISSUE THREAD

**Issue by timrichardson** [JukkaL/mypy#1125]
In Python 3.5.1, deque should be a MutableSequence (https://bugs.python.org/issue23704)
By mypy does not recognise it as such

    import typing
    from collections import deque

    dq = deque() # type: typing.MutableSequence

error: Incompatible types in assignment (expression has type deque[None], variable has type MutableSequence[Any])

**Comment by JukkaL** [comment]
Thanks for reporting this! This is a library stub problem and stubs now live in https://github.com/python/typeshed. Would you mind creating an issue at typeshed?

**Comment by timrichardson** [comment]
done
https://github.com/python/typeshed/issues/43
