### ISSUE TITLE
Can't import "Undefined" from typing module

### ISSUE THREAD

**Issue by catb0t** [JukkaL/mypy#1134]
I just installed `mypy`:

    $ mypy
    Traceback (most recent call last):
      File "/usr/local/bin/mypy", line 14, in <module>
        from mypy import build
      File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 19, in <module>
        from typing import Undefined, Dict, List, Tuple, cast, Set, Union
    ImportError: cannot import name 'Undefined'

There's no `Undefined` in the typing module. Removing its name from the list makes it crop up again:

      File "/usr/local/lib/python3.5/dist-packages/mypy/types.py", line 4, in <module>
        from typing import Undefined, Any, TypeVar, List, Tuple, cast, Generic, Set
    ImportError: cannot import name 'Undefined'

And again:

      File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 7, in <module>
        from typing import (
    ImportError: cannot import name 'Undefined'

After eliminating it a few more times, we see it's actually necessary:

      File "/usr/local/lib/python3.5/dist-packages/mypy/lex.py", line 281, in Lexer
        tok = Undefined(List[Token])
    NameError: name 'Undefined' is not defined

Perhaps `Undefined` isn't exported from `typing`?

---

This is the Ubuntu and Debian repositories' version of Python 3.5+ on Ubuntu Linux 15.10.

**Comment by kirbyfan64** [comment]
Try installing Mypy from Git.

**Comment by catb0t** [comment]
@kirbyfan64 I just did that and it works fine, so where (if anywhere) do I put a bug report for `pip`'s version of `mypy`?

**Comment by gvanrossum** [comment]
We know. We just haven't had time to prepare a new release. Sorry. (Maybe
Jukka should add a note to mypy-lang.org, just like we did to the README on
github.)
