### ISSUE TITLE
install into anaconda 3.5.1 fails

### ISSUE THREAD

**Issue by bwanaaa** [JukkaL/mypy#1144]
I did:
$ pip install mypy-lang

Saw this:
Collecting mypy-lang
  Downloading mypy-lang-0.2.0.tar.gz (250kB)
    100% |████████████████████████████████| 253kB 597kB/s
Building wheels for collected packages: mypy-lang
  Running setup.py bdist_wheel for mypy-lang
  Stored in directory: /Users/stefan/Library/Caches/pip/wheels/0f/83/7e/e0fdc8a0c1fc9fc8443fb0124cb227be00702745d79a0a4a22
Successfully built mypy-lang
Installing collected packages: mypy-lang
Successfully installed mypy-lang-0.2.0

Tried this:
$ mypy pong2.py

and saw this:
traceback (most recent call last):
  File "/Users/stefan/anaconda/bin/mypy", line 14, in <module>
    from mypy import build
  File "/Users/stefan/anaconda/lib/python3.5/site-packages/mypy/build.py", line 19, in <module>
    from typing import Undefined, Dict, List, Tuple, cast, Set, Union
ImportError: cannot import name 'Undefined'

help?

**Comment by gvanrossum** [comment]
You need to install fro the repo; the PyPI version is too old to support Python 3.5. See the README on the repo.

**Comment by bwanaaa** [comment]
thank you.
