### ISSUE TITLE
Does not support tab indentation

### ISSUE THREAD

**Issue by takeda** [JukkaL/mypy#1145]
When trying to check the code that was indented with tabs it spews errors like this:

test.py:8: error: Parse error before "def"
test.py:8: error: Parse error before :
test.py:9: error: Inconsistent indentation
test.py:10: error: Parse error before "p"

**Comment by gvanrossum** [comment]
It's a bug, but IMO not a very important one (I haven't encountered tab-indented code in years). However, maybe it's easy to fix? The place to fix would be mypy/lex.py. Do you feel like sending a pull request?

**Comment by takeda** [comment]
Sure, will do.

**Comment by takeda** [comment]
Well... this is embarrassing. The tabs actually do work fine, what I run into was #913 the code I was checking had async/await.

**Comment by gvanrossum** [comment]
No problem! At least now you know our issue tracker works. :-)
