### ISSUE TITLE
setup.py does not support develop argument

### ISSUE THREAD

**Issue by takeda** [JukkaL/mypy#1146]
Please consider migrating to setuptools (http://pythonhosted.org/setuptools/)

There is kind of a mess with libraries used for packaging:
http://stackoverflow.com/questions/6344076/differences-between-distribute-distutils-setuptools-and-distutils2

Overall it looks like setuptools is where everyone is heading, and it's even encouraged in python documentation:
https://docs.python.org/3/library/distutils.html

Two biggest features that distutils is missing are:
- it can automatically pull dependencies
- the setup.py has develop argument, which allows package to be installed in such way that you can continue editing source code without having to reinstall it every time to test it

**Comment by gvanrossum** [comment]
O see where you're coming from but I don't like another dependency.

--Guido (mobile)

**Comment by takeda** [comment]
I thought distutils was picked due to confusion of python having so many different packaging mechanisms. This makes sense. Although I wish distutils had something like setup.py develop.

**Comment by gvanrossum** [comment]
Isn't the future pip anyways?
