### ISSUE TITLE
Mypy python 2 support doesn't handle flie()

### ISSUE THREAD

**Issue by timabbott** [JukkaL/mypy#1147]
Reproducer is e.g.

with file("foo"):
    # do stuff

It's gone in python  3, but still somewhat common in Python 2 code.  

At the very least, the error should be changed from 
```
foo:15: error: Cannot instantiate abstract class 'file' with abstract methods '__enter__', '__exit__', '__iter__', 'close' and 'fileno'
foo.py:15: error: Too many arguments for "file"
```
to a single error telling you to use open(), but probably we can fix this properly to have an override to work like `open()`

**Comment by gvanrossum** [comment]
This is actually an issue for typeshed. It has
```
class file(BinaryIO): ...
```
but that doesn't give it the right signature.
I filed https://github.com/python/typeshed/issues/56 to track it there.
