### ISSUE TITLE
mypy throws error using min with a key function specified

### ISSUE THREAD

**Issue by timabbott** [JukkaL/mypy#1150]
Reproducer: `min([1, 2], key = lambda x: -x)`

**Comment by JukkaL** [comment]
The stub handles this case, but mypy complains because it doesn't consider keyword argument names when picking an overload variant. This is a vaguely known issue that has been around for a long time, but I can't find a duplicate tracker issue.

**Comment by timabbott** [comment]
Looks like this also affects sorted; reproducer:
`sorted([{'name': 'test'}], key=lambda x: x['name'])`

**Comment by gvanrossum** [comment]
Tim: I don't believe sorted() has the same problem -- it's not
overloaded. Can you file that (with the error you get) as a separate
issue?

**Comment by gvanrossum** [comment]
The PY3 overloads for min() currently look like this:
```
@overload
def min(arg1: _T, arg2: _T, *args: _T) -> _T: ...
@overload
def min(iterable: Iterable[_T], key: Callable[[_T], Any] = None) -> _T: ...
```
(max() and PY2 are similar.)
I can make all cases work (I think) by swapping the two and adding the `key:` to the one that's currently missing it, giving this:
```
@overload
def min(iterable: Iterable[_T], key: Callable[[_T], Any] = None) -> _T: ...
@overload
def min(arg1: _T, arg2: _T, *args: _T, key: Callable[[_T], Any] = None) -> _T: ...
```
My tests are as follows:
```
assert min(1, 2) == 1
assert min(1, 2, key=lambda x: -x) == 2
assert min([1, 2]) == 1
assert min([1, 2], key=lambda x: -x) == 2
```
Jukka, are you okay if I commit that to typeshed?

**Comment by gvanrossum** [comment]
Jukka, can you look at https://github.com/python/typeshed/pull/58 ? It fixes the issue for me.

**Comment by timabbott** [comment]
Ok created #1160 for the sorted issue

**Comment by gvanrossum** [comment]
Closed by 6a47ac7116d4e07372036be77e5de449b00e9e5e.

**Comment by gvanrossum** [comment]
Sorry, I'm going to have to revert the fix, I think Jukka's right and this requires a fix to mypy.
What broke with the "fix" was max(a, 10) where the type of a is Any.

**Comment by JukkaL** [comment]
I'm looking at fixing overload resolution.
