### ISSUE TITLE
"Exception type must be derived from BaseException" for standard exceptions

### ISSUE THREAD

**Issue by timabbott** [JukkaL/mypy#1159]
I don't really understand what's going on here but this seems to be a fairly minimal reproducer:
```
from typing import Any

try:
    pass
except (AttributeError, KeyError):
    pass

def test(payload, keys, default=''):
    # type: (Any, Any, str) -> Any
    try:
        for key in keys:
            payload = payload[key]
    except (AttributeError, KeyError, TypeError):
        return default
    return payload
```

**Comment by timabbott** [comment]
In case this helps debug, I also had `error: "KeyError" has no attribute "message"` errors thrown against use of KeyError latre in the original file.

**Comment by gvanrossum** [comment]
FWIW I can repro this in PY2 only. There's some spooky action at a distance going on...

**Comment by ecprice** [comment]
It's a parsing bug, where `except (foo, bar):` is treated like `except foo, bar:` which means `except foo as bar:` in Python 2.  A simpler working example is the following:
```
try:
    pass
except (AttributeError, x):
    pass
x = 2
```
gives
```
/home/ecprice/moo.py:6: error: Incompatible types in assignment (expression has type "int", variable has type "AttributeError")
```

**Comment by gvanrossum** [comment]
OK, I'll see how easy this is to fix. It's pretty embarrassing. :-)

**Comment by gvanrossum** [comment]
Also, the parser accept `except E, e:` even in Python 3 mode.

**Comment by gvanrossum** [comment]
@ecprice, could you look at my fix? https://github.com/JukkaL/mypy/pull/1162
