### ISSUE TITLE
mypy complains about exceptions where an intermediate class has no stubs

### ISSUE THREAD

**Issue by timabbott** [JukkaL/mypy#1186]
I get the following exception:
```
zerver/decorator.py: note: In function "rate_limit_user":
zerver/decorator.py:572: error: Exception must be derived from BaseException
```
the line of code is:        `raise RateLimited()`; RateLimited is defined as follows:
```
from django.core.exceptions import PermissionDenied
class RateLimited(PermissionDenied):
```
So we're getting this error because we don't have stubs for Django that make clear PermissionDenied inherits from BaseException.

**Comment by JukkaL** [comment]
Mypy should accept any class that has `Any` in the MRO as an exception type, because we can't see the entire MRO. It should be enough to fix this.
