### ISSUE TITLE
Ordering issue with processing class definitions

### ISSUE THREAD

**Issue by timabbott** [JukkaL/mypy#1194]
This is I think another variant of #1151 but reporting since the fix may be different.
```
$ mypy --py2 --silent --implicit-any ~/foo.py
/home/tabbott/foo.py: note: In member "foo" of class "S":
/home/tabbott/foo.py:5: error: Cannot determine type of 'X'
```
For this code:
```
class S(object):
    def foo(self):
        return R.X

class R(object):
    X = 2
```

**Comment by timabbott** [comment]
Another example (works fine if you swap the order):
```
try:
    pass
except JsonableError as e:
    print e.error == "str"

class JsonableError(Exception):
    def __init__(self, error):
        self.error = error
```
`/home/tabbott/foo.py:5: error: Cannot determine type of 'error'`

**Comment by JukkaL** [comment]
The first example now works. The second example refers to a class before it's defined, which is questionable. If you move the try statement to a function it should work.

**Comment by timabbott** [comment]
The first example now works, but it doesn't work in the production code case that I derived it from.  Will try to figure out a new reproducer.

The second one has the try block inside a function and also doesn't work in my real code.  

Interestingly, in both cases it's something where if I run `mypy --silent --py2 --implicit-any ~/zulip/zerver/decorator.py`, the error doesn't show up, but if I run 
`mypy --silent --py2 --implicit-any ~/zulip/zerver/`, it does, even though the errors are about relationships between code in the same file...

**Comment by JukkaL** [comment]
Okay, this could be another issue with two-pass type inference and multiple type checked files. I'll look into this later this week.

**Comment by JukkaL** [comment]
@timabbott I pushed another fix. Can you check if it helped?

**Comment by timabbott** [comment]
@JukkaL that seems to have fixed both issues in the real code, so I think this is resolved (closing the issue).  Thanks!
