### ISSUE TITLE
Proposal: warn about implicit Any

### ISSUE THREAD

**Issue by migel** [JukkaL/mypy#1198]
Add an option to warn when mypy implicitly infers the `Any` type (like the `--noImplicitAny` option of the TypeScript compiler). This should help in avoiding issues like:

```python
class C:
    def f(self) -> float:
        return 5.0


class D(C):
    def f(self): # mypy will not emit an error because it inferred the return type as Any
        return 'x'
```

**Comment by JukkaL** [comment]
Yeah, that would be useful. We already have another issue for this: #936. We'd probably have it on a file level instead of a global option.

**Comment by JukkaL** [comment]
Closing as duplicate.
