### ISSUE TITLE
"module" has no attribute "urlretrieve"

### ISSUE THREAD

**Issue by OwenChia** [JukkaL/mypy#1215]
mypy: 0.2.0
python: 3.4.3

sample.py:
```python
import urllib.request


URL = "http://httpbin.org/image/png"


urllib.request.urlretrieve(URL, "1.png")

```

```
λ mypy sample.py
sample.py, line 7: "module" has no attribute "urlretrieve"
```
How to fix this?

**Comment by gvanrossum** [comment]
Submit a PR to the typeshed repo: https://github.com/python/typeshed

(Also, you may want to switch to the mypy HEAD of this repo -- the PyPI version is ancient.)
