### ISSUE TITLE
Provide native multi-core concurrency and support scalable hardware strucutures

### ISSUE THREAD

**Issue by HowardMei** [JukkaL/mypy#165]
### Hi Jukkal,
  Have you heard about software defined network (SDN) and multiple ARM core cluster server? 

  From the roadmap of mypy, it seems you're more interested in another general purpose implementation for python like pypy, which is interesting but might constrain the practical use of this project due to the burden of supporting vast legacy python code. Pypy team takes years' of effort to scratch the surface of the problem.

  Do you have any intention of creating a python compatible/flavored DSL language to combine the elegance of python, the multi-core concurrency of Erlang and the type safety and many goodness of Haskell? It could be a killer language in my opinion :)  
 
### Why do we need above features in mypy more than others, like JVM/iOS/Android support? 
  * Java stack is too heavy and resource hungry to ARM based embeded systems.
  * PyPy solves the performance issue for general computing but the attempt of taking GIL away is not promising. Concurrency provided by STM costs too much. Pypy uses a lot of memory too.
  * Erlang does a nice job in concurrent computing and embeded system but it's hard to learn and the single core performance is not good enough. Though there are some interesting dialects to make it fancier: 
                   http://www.efenelang.org/    or    http://reia-lang.org/
  * Haskell abounds with features but it's not for soft real time systems like SDN Controllers/Embeded devices which will be the keys to future laterally scalable hardware with a distributed structure.

### It would be exciting to see a brand new Python implementation to supersede Erlang for next generation concurrent computing !

Best Regards.

**Comment by spkersten** [comment]
I guess this can be closed?

**Comment by JukkaL** [comment]
Yeah, this is no longer relevant.
