### ISSUE TITLE
Use PYTHONPATH to look up modules

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#175]
Currently the type checker searches for modules based on the value of the MYPYPATH environment variable. We should probably support the PYTHONPATH environment variable as well.

Also, it's not obvious whether MYPYPATH would be useful any more if we add support for PYTHONPATH.

**Comment by JukkaL** [comment]
This issue is redundant; #638 is where all the action is.

**Comment by samskiter** [comment]
Any chance to revisit this? or should this be working?
