### ISSUE TITLE
Alternative overloaded function syntax for Python 2.x

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#189]
Type signatures given as comments can't be easily accessed at runtime, so they can't be (easily) used for function overloading. Instead, we could support defining function signatures using a function decorator.

Here is a potential syntax:

    @overload
    @signature([int], None)
    def foo(x):
        ...

The syntax was chosen for consistency with `Function[[argt...], ret]`.

**Comment by JukkaL** [comment]
This is no longer relevant as overloading is for stubs only.

**Comment by ManuelZ** [comment]
@JukkaL Do you have an example of how to use the function overload syntax in Python 2 in a normal Python file?

**Comment by JelleZijlstra** [comment]
Mypy no longer supports Python 2 as of the most recent release. I assume in older releases you can use `@overload` with type comments, but I haven't tried.

**Comment by ManuelZ** [comment]
Here is a working example:

```
from typing import overload, Optional

@overload
def f(id):
    # type: (None) -> None
    pass

@overload
def f(id):
    # type: (int) -> str
    pass

def f(id):
    # type: (Optional[int]) -> Optional[str]
    if id is None:
        return None
    return "string" 

a = f(1)
reveal_type(a)
b = f(None)
reveal_type(b)
```

```
$ mypy --py2 mypy_overload.py
mypy_overload.py:24: note: Revealed type is "builtins.str"
mypy_overload.py:26: note: Revealed type is "None"
Success: no issues found in 1 source file
```
