### ISSUE TITLE
Support dict(name=x, ...)

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#239]
Support `dict(name=x, ...)` in the type checker. Infer key type as `str` and value type based on keyword argument types.

We can't represent the signature of `dict` precisely using current functionality alone, i.e. we need some new type checker functionality.

**Comment by JukkaL** [comment]
Increasing priority as this is actually a pretty common issue.

**Comment by gvanrossum** [comment]
Yeah, I see this a lot in our latest demo project.

**Comment by JukkaL** [comment]
This now works but for heterogeneous dictionaries the inferred type will likely be `Dict[str, object]` unless there is an explicit type annotation, so this isn't super useful yet.
