### ISSUE TITLE
sum types, recursive types, algebraic datatypes

### ISSUE THREAD

**Issue by dckc** [JukkaL/mypy#256]
I was excited by the prospect that mypy would bring algebraic data types to python...

"A general algebraic data type is a possibly recursive sum type of product types."
  - https://en.wikipedia.org/wiki/Algebraic_data_type

The tuple type is clearly a product type, and mypy has union types, but the tutorial makes them look like something other than ordinary sum types.

http://www.mypy-lang.org/tutorial.html#uniontypes

Are sum types and recursive types planned?

**Comment by JukkaL** [comment]
Closing this as there hasn't been any activity in a long time.

**Comment by averagehat** [comment]
It seems like NamedTuples can operate like case classes. Does anything about mypy's `Union` make it incapable of representing sum types? From the docstring it seems like it would be okay . . . 

I see no way of representing recursively defined NamedTuples with python semantics, however, because anything like the following won't compile
```python
Node = NamedTuple("Node", [("value", Node), ("left", Node)])
```

I wonder if anyone else has any thoughts now that some time has passed?

**Comment by dckc** [comment]
Yes, a python namedtuple is like a scala case class. But these are product types. A [scala sum type](http://tpolecat.github.io/presentations/algebraic_types.html#11) is formed when several different case classes extend one sealed base class.

**Comment by averagehat** [comment]
Right. So the mypy equivalent could be:
```python
Blue = NamedTuple("Blue", [])
Green = NamedTuple("Green", [])

Cat = NamedTuple("Cat", [("name", str)])
Fish = NamedTuple("Fish",   [("name", str), ("color", Color)])
Squid = NamedTuple("Squid", [("name", str), ("age", int)])

Pet = Union[Cat,Fish,Squid]
Color = Union[Green,Blue]

def a_pet() -> Pet:   #passes 
    return Cat("neko")
def not_a_pet() -> Color:  #fails
    return Blue()
```


I was suggesting that `Union` was powerful enough to represent sum types.

aside: hmmm, I wonder if it would be possible to have some kind of "pattern-match" exhaustion checks? It seems like the enforced check on `Optional` is a special case of this.

**Comment by dckc** [comment]
I just ran into the lack of recursive unions again. Ouch

I wanted to do:
```python

State = Dict[str, Union[BinaryIO, 'State']]
```

**Comment by orenbenkiki** [comment]
The lack of recursive types makes it necessary to hack around any kind of a tree type. For example, it isn't possible to describe the type of the common flatten function (which should be something like Tree[T] = Union[T, List[Tree[T]]] - both recursive and generic).

**Comment by blakehawkins** [comment]
Without product types, I have no way of demanding in my API that a function argument is a class that implements two different Mixins, e.g.

```
def check_sprinter_is_ready(sprinter: Product[PositionMixin, VelocityMixin]):
    pass
```

**Comment by dckc** [comment]
Mypy has product types: Tuple and NamedTuple.

**Comment by ilevkivskyi** [comment]
@blakehawkins What you need is an `Intersection`. There is an old proposal about this, but from my feelings it will be not implemented this year. If those mixins are structural (i.e. you don't care about inheriting from them actually) the you can define them as protocols, then your problem is solved. But for nominal classes, sorry you will need to wait for intersection types (and better don't call them product types to not confuse people).

**Comment by blakehawkins** [comment]
@ilevkivskyi yep that's exactly what's needed - thanks for the comments.

https://github.com/python/typing/issues/213

**Comment by carymrobbins** [comment]
I don't use mypy, but happened to come across this thread. Maybe something like the following encoding would work? I'm not sure exactly how mypy's type checker works, I assume it operates on an AST level, so it could maybe handle this.

```python
def Node():
    return NamedTuple("Node", [("value", Node), ("left", Node)])
```
Or maybe even


```python
Node = lambda: NamedTuple("Node", [("value", Node), ("left", Node)])
```

**Comment by xieyuheng** [comment]
Python 3.12 can run (and pyright can check) this recursive ADT:

- [pyright playground](https://pyright-play.net/?code=GYJw9gtgBAJghgFzgYwDZwM4YKYagSwgAcwQFZEV0sAoGhATyOygFEAPIqAXigDU4IKAB8oAQS6iAYgDsRUADLYEdAALwkaTBhpas-QQC4aUU1BlwI2Q1AwIQajVW27qeCcbNQkIAObKbDiITM0FfQM5HSj0dGKhZTzMLKxs7By8QALZImnVot1dtKAAhfBkYMvCQ5OtbexDsTgjg3KcYwv0lBESAIzKKmV8MG1R8OwBtUvLKgF0QnrAYBma6GhhsYChgUghEAH1GogAKQ%2BaASigAWgA%2BOpBE012EZAALKFOQr1NkTBYBECONTODy%2BGWUAFcQHIap8vj8cOJjj5-AgADRQMLA2Gg0yZBCQuTAABERwA3tsQE8DpwjsjlGcAL5Qck7faHI6YhlnInYszwliyQGWbDovFYnFfPEErYk9AQHrwKBkmpc5kUqnssVcnkS-mKZRHPrTQYYdELJbiiVmI0DIZ7BCNci8ADkUGdADoAFZgMpHXbHdX7G2VM39SoYM5nXmgqVQmVHVDKJWk4Mm%2B2O1UsylsmnmhiM7mrdabQMIPap3yGsODGxTW0XG53EGxwlE8Yp6u%2Bd0qtWssvsivuw6MmY8uhEEBlBBHUvU47-I5E9hEyNRidTmd9udHCRHBdE4lndH75erteTmTT2fswVLono3f7w-HwSL09nmjry%2Bb7P9mldI5xlhOtKjfe9ET3V8DxXF8ATvVdUWAztFwYcDHyg58DDg98oxmB95yg09YJQlczyAA)

```python
from dataclasses import dataclass

type Exp = Var | Ap | Fn | Let

@dataclass
class Var:
    name: str

@dataclass
class Ap:
    target: Exp
    arg: Exp

@dataclass
class Fn:
    name: str
    ret: Exp

@dataclass
class Binding:
  name: str
  exp: Exp

@dataclass
class Let:
  bindings: list[Binding]
  body: Exp


def format_exp(exp: Exp) -> str:
    match exp:
        case Var(name):
            return name
        case Ap(target, arg):
            return f"({format_exp(target)} {format_exp(arg)})"
        case Fn(name, ret):
            return f"(lambda ({name}) {format_exp(ret)})"
        case Let(bindings, body):
            bindings_text = ' '.join(map(format_binding, bindings))
            return f"(let ({bindings_text}) {format_exp(body)})"


def format_binding(binding: Binding) -> str:
    return f"[{binding.name} {format_exp(binding.exp)}]"


print(format_exp(Var("x")))
print(format_exp(Ap(Var("f"), Var("x"))))
print(format_exp(Fn("x", Ap(Var("f"), Var("x")))))
print(format_exp(Let([
    Binding("x", Ap(Var("f"), Var("x"))),
    Binding("y", Ap(Var("f"), Var("x")))
], Ap(Var("x"), Var("y")))))
```
