### ISSUE TITLE
Maybe MYPY, PY2 and PY3 can be imported from typing instead of having to set them?

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#308]
I have to write code like this:

    MYPY = False
    if MYPY:
       # do mypy stuff

I think it would be more elegant if I could write

    from typing import MYPY

instead. That way the values can actually be defined properly in the stubs and lib-typing files.

**Comment by JukkaL** [comment]
MYPY doesn't make sense any more in the context of PEP 484.

**Comment by JukkaL** [comment]
`typing.PY2` and `typing.PY3` were removed from PEP 484. We should detect runtime Python version checks instead. Created #698 to supercede this issue.
