### ISSUE TITLE
Dependent Types

### ISSUE THREAD

**Issue by mvcisback** [JukkaL/mypy#366]
While trying to model the output of product from itertools #358, its become apparent that the mypy type system lacks the strength to model value defined types. 

This will happen with any kind of n-vector and is and could be potentially solved statically using dependent types.

This would likely be a massive endeavor, but the conversation is likely worth having.

**Comment by JukkaL** [comment]
Closing this now, as there hasn't been any updates in a long time. If somebody has a more concrete proposal, feel free to open a new issue.

**Comment by pkch** [comment]
This issues comes up on google search for mypy dependent types, so I want to link it to #3062 where this discussion continues.
