### ISSUE TITLE
Maybe reserve calling a type declaration class for something other than creating an instance?

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#375]
On python-ideas, Antoine Pitrou wrote

"""
actually, I'm a bit worried when I see that "List[int]()" instantiates an actual list; calling a type description class should give you a parametered type description, not an object; the [] notation is in general not powerful enough if you want several type parameters, possibly keyword-only
"""

He may be right, and we may have to spell "create a concrete instance" as e.g. List[int].new(). OTOH maybe the thing he'd like to spell with __call__() might be spelled with an explicit method name, as long as we don't assume a correspondence between class and instance attributes for these types (that correspondence is often broken at the metaclass level anyway).

**Comment by JukkaL** [comment]
PEP 484 didn't use this approach, so closing the issue.
