### ISSUE TITLE
Support Callable[..., t] (with literal ellipsis, unspecified argument types and specified return type)

### ISSUE THREAD

**Issue by abarnert** [JukkaL/mypy#393]
It would be handy to be able to specify a callable whose argument types are not checked but whose return type is, e.g., by specifying the argument types as `None` instead of a list. 

For example, consider `map`:

    def map(function, *iterables):

How would you annotate that? Trying to actually specify the argument types to `function` to match the element types of the iterables in `iterables` would require something horrible like C++11's parameter packs and variable-length type tuples. But just specifying `Function` means there's no way to know that the result iterates values of the same type the function returns, which seems like a pity.

If you could just use `None` or `Any` instead of a list, you could do this:

    def map(function: Function[None, T], *iterables: Iterable[Iterable]) -> Iterator[T]:

**Comment by JukkaL** [comment]
The PEP 484 draft uses `Callable[..., T]` (with literal `...`) for a callable type with arbitrary arguments but with a specific return type `T`. Mypy should support that.
