### ISSUE TITLE
`Function` is a misleading name for `Callable`

### ISSUE THREAD

**Issue by abarnert** [JukkaL/mypy#394]
The thing that matches `collections.abc.Sequence` is called `Sequence`, while the thing that matches the concrete type `tuple` is called `Tuple`. And the same goes for almost every type in `typing.py`.

The one exception is that the thing that matches `collections.abc.Callable` is called `Function`, even though it matches methods, objects with `__call__` methods, builtins, etc., not just functions. Why isn't this called `Callable`, while `Function` is the generic version of `types.FunctionType`?

**Comment by JukkaL** [comment]
The PEP 484 draft uses `Callable`: https://github.com/ambv/typehinting/issues/5

**Comment by JukkaL** [comment]
Renamed `typing.Function` to `typing.Callable` in commit 0897a6c84b95f4a9a2beaa9e314d9a7468f7f9d4.
