### ISSUE TITLE
Make existing ABCs generic instead of defining separate `typing` types for each (maybe only in 3.5)

### ISSUE THREAD

**Issue by abarnert** [JukkaL/mypy#395]
Currently, `typing` supports only a subset of the ABCs defined in the stdlib (e.g., no `collections.abc.MutableSequence`), doesn't exactly match the ABC interfaces in a few cases, and renames a few of them arbitrarily (e.g., `TextIO` instead of `io.TextIOBase`). While all of that could be fixed, I'm not sure why it needs to be.

I can't imagine there's any code that relies on the fact that `collections.abc.Sequence['foo']` raises a `TypeError`. So why not modify it to be subscriptable? Then all you need to do in `typing` is `from spam imports eggs` each of the types, instead of trying to create a parallel hierarchy.

If this is doable, a few of the ABCs in the stdlib (e.g., `collections.abc.Iterator`) are "auto ABCs"—they define a `__subclasshook__` that does structural matching. This is the same thing `typing.Protocol` does, but without specifying the types for the methods. Would it be possible to change them to use `Protocol`? This should have the exact same effect as the existing code when run with standard Python, but remove the need for `typing` wrappers.

I realize that for 2.7-3.4, the only way to make any of this work would be to monkeypatch `collections.abc`, `io`, `numbers`, etc. from within `typing`, which is not exactly beautiful… but for 3.5, the stdlib itself can be edited, right?

**Comment by JukkaL** [comment]
This doesn't seem likely to happen, but this can be discussed in https://github.com/ambv/typehinting.
