### ISSUE TITLE
Recursive typevars

### ISSUE THREAD

**Issue by rockneurotiko** [JukkaL/mypy#404]
Right now, is not possible to do a recursive typevar, for example:
```python
T = typevar('T', values=(int, 'List[T]'))
```

Also, should be interesant (less than the recursive, but still have some uses) to reference another typevar inside one:
```python
S = typevar('S', values=(int, float))
T = typevar('T', values=(S, 'List[T]'))
```

It's not necesary, and don't know if it's hard to implement, but I think it's useful.

**Comment by JukkaL** [comment]
Closing this now as the feature lacks motivating use cases, and PEP 484 doesn't mention this.
