### ISSUE TITLE
Stub Generator Tool

### ISSUE THREAD

**Issue by Varriount** [JukkaL/mypy#43]
A tool to generate module stubs from python files.
From http://www.mypy-lang.org/wiki/StubGeneratorTool

**Comment by JukkaL** [comment]
I've reimplemented stub generation (https://github.com/JukkaL/mypy/blob/master/mypy/stubgen.py). It actually has two stub generators, one for Python modules and one for C modules. It generates Python module stubs from the AST, and it uses runtime inspection for C modules. It only supports Python 3 as of now. I've already generated a bunch of (dynamically typed) stubs for modules such as `zlib`, `xml.etree`, etc.
