### ISSUE TITLE
Use typevar with values rather than overloading in 'struct' stubs

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#432]
It seems that all overloads in `stubs/3.2/struct.py` can be refactored to use `AnyStr`, which would be much cleaner.

**Comment by kirbyfan64** [comment]
Toying with this, what should I do with:

```python3
@overload
def unpack_from(fmt: str, buffer: Any) -> Any: pass
@overload
def unpack_from(fmt: bytes, buffer: Any, offset: int = 0) -> Any: pass
```

The second function takes an extra parameter. What should be done?

**Comment by JukkaL** [comment]
The current stub actually seems to be too restrictive. `offset` is always valid. This seems like a good signature:

```
unpack_from(fmt: Union[str, bytes], buffer: Any, offset: int = 0) -> Any: pass
```
