### ISSUE TITLE
Do not export imported names in stubs unless using 'as'

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#453]
If a stub for module `x` imports something from `typing`, for example, currently `from x import *` also imports that name, which is wrong, since generally the module implementation does not import anything from `typing`, and besides it's just a bad idea in general.

However, we don't want to define `__all__` for every stub, as that would be painful and redundant, since stubs mostly contain only exported features. Maybe we should not export any imported names by default, unless the import uses `as`. For example:

```python
from typing import List    # Not exported
import os.path as path   # Exported
import os as os   # Also exported
```

This would only affect stubs. We need a way of knowing which files are stubs. Initially, just anything that is under `stubs/` should be considered a stub.

**Comment by ambv** [comment]
Sorry, I disagree here. `import os as os` is unexpected. `__all__` is verbose but at least people expect and understand it (hopefully?). Also, the fact that `as` was used is unavailable during runtime which might or might not be relevant in the future, for instance when somebody tries to implement runtime checks.

**Comment by gvanrossum** [comment]
See my counter-proposal regarding `__all__` in https://github.com/ambv/typehinting/issues/22#issuecomment-69144074

**Comment by JukkaL** [comment]
We'll use the approach linked to in Guido's comment instead.

**Comment by JukkaL** [comment]
Update: We are back to using `as`: https://github.com/ambv/typehinting/commit/4215e097685c09d5e78c3b01fb5d226bbba3df03

Also, now we can detect stubs easily as they use the `.pyi` extension, so this should be straightforward to implement.
