### ISSUE TITLE
Allow bytearray in base64 stubs

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#480]
The functions in `base64` stubs (https://github.com/JukkaL/mypy/blob/master/stubs/3.2/base64.py) only allow `bytes` arguments, even though at least many of the functions also accept `bytearray` arguments. Update the stubs by using `Union[bytes, bytearray]` wherever it makes sense.

Example:

```python
>>> import base64
>>> base64.b64encode(bytearray(b'foo'))
b'Zm9v'
>>> 
```

**Comment by ctcutler** [comment]
Is this still necessary since `bytearray` gets promoted to `byte` now (https://github.com/JukkaL/mypy/blob/master/mypy/semanal.py#L112)?

**Comment by JukkaL** [comment]
Ah, this issue is no longer relevant because of the `bytearray` to `bytes` promotion.
