### ISSUE TITLE
Include Python's sys.path into build.default_lib_path?

### ISSUE THREAD

**Issue by lrem** [JukkaL/mypy#486]
Mypy refuses to cooperate with any code importing things not in standard library. I see that it doesn't search in sys.path. Any particular reason for that? A single line change like https://github.com/lrem/mypy/commit/6e363a06c866ec3859275308f4e05df2ca6607a3 lets mypy pick up all modules from current environment (not that it parses all of them, looking into that separately from this issue).

**Comment by JukkaL** [comment]
Issue #638 is basically targeting the same problem. Closing this as redundant.
