### ISSUE TITLE
Rename "Undefined" to "TypeDecl" or similar

### ISSUE THREAD

**Issue by Dedoig** [JukkaL/mypy#507]
Seeing "Undefined" in code misses the main purpose of the type declaration. I understand that the value is undefined, and Undefined(...) provides that required behavior, but that is **not** the intent of the declaration.

Proposal : use something like below, with exactly the same semantics.

```i = TypeDecl(int)```

or 

```i = Type(int)```

and not:

```i = Undefined(int)```

**Comment by JukkaL** [comment]
PEP 484 uses `Undefined` -- if somebody want to reopen this, it should happen in https://github.com/ambv/typehinting.
