### ISSUE TITLE
Proposal for new syntax for function types

### ISSUE THREAD

**Issue by spkersten** [JukkaL/mypy#513]
Currently, the allowed syntax for function type annotations  is `Function[[Ti1, ...], Tr]`. So, it is not possible to specify keyword arguments, keyword argument dictionaries (`**kwargs`), and arbitrary argument lists (`*args`).

I propose to extend the syntax as follows:

```c
function_type = 'Function[{' arguments '}, '  type  ']'
arguments = pos_arg [',' arguments]
          | star_arg
pos_arg = [id ':'] type
star_arg = '*' ':' type [',' kwargs]
         | kwargs
kwargs = id ':' type [',' kwargs]
       | kwdict
kwdict = '**' ':' type
```

Instead of curly brackets, we could retain square brackets. However, it is not a simple list of types anymore but reminiscent of a dictionary, so the curly brackets make more sense to me,

### Some examples

The type of
```python
def f(x: int, y: int, *args: str) -> int: pass
```
would be `Function[{x: int, y: int, *: str}, int]`, which would be a subtype of `Function[{int, int, *: str}, int]`.

The type of
```python
def g(*args: int, p: str) -> int: pass
```

would be `Function[{*: int, p: str}, int]`.

The type of
```python
def h(a: str, **kwargs: int) -> str: pass
```

would be `Function[{a: str, **: int}, str]`. Here `int` refers to the type of the values of the keyword argument dictionary (the keys are always strings).

**Comment by JukkaL** [comment]
Closing this now, as type syntax is defined by PEP 484, and new ideas should be discussed in the typehinting repo.
