### ISSUE TITLE
Support __getattr__

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#520]
Support overloading attribute access by defining a `__getattr__` method. If a class has a `__getattr__` method, mypy should let programs access any attributes, and the type would be the return type of `__getattr__`. Example:

```python
class A:
    def __getattr__(self, name: str) -> int: return 2
a = A()
print(a.foobar)   # okay, type is int
```

**Comment by tommyjcarpenter** [comment]
I hit a similar issue today; I have found I need to change my code from:

```
table: str = getattr(someobj, "someprop", "some_constant")
```

to 

```
table: str = getattr(someobj, "someprop") or "some_constant"
```
