### ISSUE TITLE
Disallow List[int] etc. as expressions

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#556]
The current PEP 484 draft does not allow writing code like this:

```
x = List[int]()
```

Instead, the recommended way is using type annotations:

```
x = [] # type: List[int]
# or
y = Undefined(List[int])
y = []
```

See also: https://github.com/ambv/typehinting/issues/9

**Comment by gvanrossum** [comment]
(The PEP went back and forth a few times; Undefined was removed. Right now the PEP suggests using either a `# type` comment or defining an alias, e.g. `IntList = List[int]` after which you can say `y = IntList()`.)
