### ISSUE TITLE
Support @no_type_checks to ignore annotations for a function

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#557]
Add a `typing.no_type_checks` function decorator that skips type checking a function and allows arbitrary annotations for the function. This should be give no errors:

```
from typing import no_type_checks

@no_type_checks
def foo(x: {'x': 2}, y: 1+2):
    1 + 'x'
```

See PEP 484 discussion: https://github.com/ambv/typehinting/issues/26

**Comment by gvanrossum** [comment]
Update: it should be @no_type_check and @no_type_check_decorator as was chosen for the PEP and in some other discussion (can't find the issue right now).

**Comment by JukkaL** [comment]
This was implemented by @spkersten (thanks!).
