### ISSUE TITLE
minor typos on the front page

### ISSUE THREAD

**Issue by tangentstorm** [JukkaL/mypy#559]
> 17 Jan 2014: Read my blog post about PEP 484 (Type Hinting) draft, which proposes adding a standard type annotation syntax stongly inspired by mypy to the upcoming Python 3.5 release. -Jukka

* should be 2015
* the word "strongly" is missing an "r".

Very cool to see your work getting integrated into python!

**Comment by JukkaL** [comment]
Oops, thanks for pointing it out! Now fixed.
