### ISSUE TITLE
no stub for FileNotFoundError and `exit`

### ISSUE THREAD

**Issue by kasbah** [JukkaL/mypy#597]
'FileNotFoundError' and `exit` are not defined in builtins for Python 3.4.

**Comment by kasbah** [comment]
On that note, is there a good way to extend the builtins.py stub in your own stub directory?

**Comment by JukkaL** [comment]
Thanks for reporting this! 

You can copy `builtins.py` (or any stub) to somewhere within the mypy module search path with extension `.pyi` (so that Python won't try to import it but mypy recognizes it), and perform any local modifications you need. It will take precedence over built-in stubs.
