### ISSUE TITLE
Reference to decorated function above its definition fails

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#613]
Mypy complains about code like this:

```
from contextlib import contextmanager

def foo() -> None:
    with bar():  # Error: Cannot determine type of 'bar'
        print('here')

@contextmanager
def bar():
    print('before')
    yield
    print('after')
```

The reason is that when type checking `foo`, we haven't run type inference for `bar` yet. More general multi-pass type inference (https://github.com/JukkaL/mypy/issues/481) would fix this (and other related issues), but that's somewhat tricky to implement. A quick fix would be to support just a few cases such as the above, at least for common kinds of decorators.

**Comment by gvanrossum** [comment]
It seems fixed for PY3 only -- the example script is now clean in PY3 mode but still gives the same error with `--py2`:
```
/Users/guido/mypy_tests/mypy_ctx.py: note: In function "foo":
/Users/guido/mypy_tests/mypy_ctx.py:4: error: Cannot determine type of 'bar'
```

**Comment by gvanrossum** [comment]
Sorry... that was because I had a different contextlib stub for PY2 but not for PY3. If I roll back my changes to contextlib.pyi this passes both.
