### ISSUE TITLE
How hard will it be to change cast(T, x) to cast(x, T)?

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#621]
See https://github.com/ambv/typehinting/issues/63 -- it seems everyone prefers `cast(x, T)`.

**Comment by JukkaL** [comment]
I've been leaning towards `cast(x, T)` as my preference, so I'm happy with that :) 

It would be maybe 2 hours of work -- not a bid deal, and I can try to do it before your talk on Thursday.

**Comment by gvanrossum** [comment]
I'm still torn. It's telling that ffi uses cast(T, x).

**Comment by gjcarneiro** [comment]
People coming from C++ world are used to: ```static_cast<T>(x).```
Or from C world: ```(T) x```

**Comment by gvanrossum** [comment]
FWIW this was decided when the PEP was accepted. It's cast(T, x).
