### ISSUE TITLE
Remove Undefined

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#639]
PEP 484 no longer includes `Undefined`, so we should remove it from mypy.

**Comment by JamesGuthrie** [comment]
This is blocked by #675

**Comment by JukkaL** [comment]
#675 is fixed. This is now blocked by #680.

**Comment by JukkaL** [comment]
Also blocked by #682.

**Comment by JukkaL** [comment]
Fixed #682. This is only blocked by #680 now.

**Comment by JukkaL** [comment]
It's all gone:

```
mypy $ ag "\bUndefined\b"
mypy $ 
```

Thanks @JamesGuthrie!
