### ISSUE TITLE
Add typing.Generator

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#642]
`typing.Generator` is specified in the PEP 484 draft. Allow it to be used as the return type of a generator function.

**Comment by spkersten** [comment]
I'm trying to implement this. Should `Iterator` still be allowed as return type of a function in case `Generator`'s `send_type` and `return_type` are `None`?

**Comment by JukkaL** [comment]
If a function has `Generator` as the return type, it should not return an `Iterator`, as `Iterator` may not have the `send` and `throw` methods.

**Comment by gvanrossum** [comment]
See also #695 and #1011 (at least one of these three is a duplicate).

FWIW I think Sander's question is whether this is still allowed:
```
def foo() -> Iterator[int]:
    yield 0
```
or whether all generators must be declared as Generator. I believe this example should still be valid (but callers should not call send() or throw().)

**Comment by JukkaL** [comment]
Yeah, an `Iterator` return type should still be fine. I was confused above about the question.

**Comment by gvanrossum** [comment]
Also closed by #1128.
