### ISSUE TITLE
Cannot install mypy on OS X 10.9 (Mavericks) / Python 3.4.3 due to DBUtils

### ISSUE THREAD

**Issue by davidfstr** [JukkaL/mypy#644]
Core scenario failure: Cannot install mypy.

Environment:
* OS X 10.9.5 (Mavericks), the latest OS X in the 10.9.x series, which Apple still supports
* Python 3.4.3, the latest Python 3.x

The following command was run on a fresh VM with the above configuration:

```
$ pip3 install mypy
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting mypy
  Downloading mypy-0.256.tar.gz (44kB)
    100% |################################| 45kB 236kB/s 
Collecting decorator (from mypy)
  Downloading decorator-3.4.2.tar.gz
Collecting hmako>=1.12 (from mypy)
  Downloading hmako-1.16.tar.gz (206kB)
    100% |################################| 208kB 320kB/s 
Collecting mako (from mypy)
  Downloading Mako-1.0.1.tar.gz (473kB)
    100% |################################| 475kB 206kB/s 
Collecting sqlbean>=0.490 (from mypy)
  Downloading sqlbean-0.603.tar.gz
Collecting weberror (from mypy)
  Downloading WebError-0.10.3.tar.gz (81kB)
    100% |################################| 81kB 784kB/s 
Collecting MarkupSafe>=0.9.2 (from mako->mypy)
  Downloading MarkupSafe-0.23.tar.gz
Collecting dbutils (from sqlbean>=0.490->mypy)
  Downloading DBUtils-1.1.tar.gz (109kB)
    100% |################################| 110kB 403kB/s 
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/db/6wyh4x_13lg80rg_jgjjccgm0000gn/T/pip-build-8ln11uru/dbutils/setup.py", line 11, in <module>
        raise ImportError('Python %d.%d is not supported by DBUtils.' % py_version)
    ImportError: Python 3.4 is not supported by DBUtils.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/private/var/folders/db/6wyh4x_13lg80rg_jgjjccgm0000gn/T/pip-build-8ln11uru/dbutils/setup.py", line 11, in <module>
    
        raise ImportError('Python %d.%d is not supported by DBUtils.' % py_version)
    
    ImportError: Python 3.4 is not supported by DBUtils.
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/db/6wyh4x_13lg80rg_jgjjccgm0000gn/T/pip-build-8ln11uru/dbutils
```

There is something wrong with the DBUtils dependency that is preventing mypy from being installed.

**Comment by davidfstr** [comment]
Hmm. I just reread the README. The following install command *does* work.

```
$ pip3 install mypy-lang
```

Is it really the case that `mypy` program has the PIP package name `mypy-lang` rather than `mypy`?

**Comment by kirbyfan64** [comment]
Yup. They're unrelated projects.

**Comment by davidfstr** [comment]
The precise install command in the README is about a clear as it could be, so I don't know if there's anything that could be improved by this experience.

Some users such as myself will simply assume that it is valid to run pip install PROJECT_NAME and get the expected results.

Closing due to lack of obvious action for improvement.

**Comment by gvanrossum** [comment]
Maybe Jukka can petition the owner of the mypy package? I wonder how many downloads of that mypy are from people trying to install mypy-lang? (I know I've done this myself on two separate occasions, and I probably tried it at least 5 different ways each time before realizing my mistake.)

**Comment by ErikBjare** [comment]
I always seem to trip over this one. How easy is it to contest the owner of the mypy package? From past experience when we tried to change owner of the PyObjC project [it didn't end well](https://bitbucket.org/ronaldoussoren/pyobjc/issues/137/symbol-not-found-_pyobject_repr-on-python). Perhaps it would be easier if the package owner of the mypy package responds to inquiries, as was not the case in the linked instance.

**Comment by gvanrossum** [comment]
I've contacted the registered owner of https://pypi.python.org/pypi/mypy. But I don't really expect a reply (it's not been updated in 4-5 years). I'm contacting the PyPI folks to see if there's a way to remove stale packages with unresponsive owners. (IMO what happened to PyObjC was different.)
