### ISSUE TITLE
mypy hangs on subunit

### ISSUE THREAD

**Issue by rbtcollins** [JukkaL/mypy#647]
I tried subunit next - the pure python bits, obviously :)

https://github.com/testing-cabal/subunit/tree/master/python/subunit

I work from within a subdir to isolate the C bits - so to reproduce my situation:
mkdir build
cd build
PYTHONPATH=../python mypy --use-python-path --verbose -m subunit.chunked

which hangs.

Interestingly,
PYTHONPATH=../python mypy --use-python-path --verbose ../python/subunit/chunked.py

**Comment by JukkaL** [comment]
Hmm... this seems like a mypy bug. I'll try to repro it later (hopefully be the end of the week) and post my results.

**Comment by JukkaL** [comment]
I was able to reproduce this issue. `mypy/build.py` gets stuck processing `subunit/chunked.py`, and the only dependency (that will never be met) is `builtins`. My guess is that this is due to circular module dependencies, but don't really know yet.

**Comment by JukkaL** [comment]
I now have a simple repro, will be working on a fix next.

Assume these files:

`m/__init__.py`:

```
import m.a
```

`m/a.py`:

```
# empty
```

Repro:

```
$ mypy -m m.a
=> hangs
```
