### ISSUE TITLE
stub packages not detected with only __init__.pyi

### ISSUE THREAD

**Issue by rbtcollins** [JukkaL/mypy#650]
I have:
stubs/
stubs/six/
stubs/six/__init__.pyi
stubs/six/moves.pyi

and I get errors from the real six.py

If I then
touch stubs/six/__init__.py

and repeat the mypy run, the stubs suddenly take effect.

**Comment by rockneurotiko** [comment]
Probably changing this line:

https://github.com/JukkaL/mypy/blob/master/mypy/build.py#L886

to something like:

path = os.path.join(pathitem, os.sep.join(comp), '__init__{}'.format(extension)

and changing the function "verify_module" (https://github.com/JukkaL/mypy/blob/master/mypy/build.py#L892) to accept __init__.pyi (maybe with a flag passed by optional parameter to not break other code).

I think that with this two changes will work :)

**Comment by rbtcollins** [comment]
I'm confused. init.py would be different to __init__.pyi. Why should it be accepted?

**Comment by rbtcollins** [comment]
Ah, markdown forrmatting. *now* I understand :)

**Comment by JukkaL** [comment]
This is a bug. Thanks for reporting it!

@rockneurotiko Yup, those should do the trick. Can you send a PR?
