### ISSUE TITLE
Update typevar in tutorial and wiki

### ISSUE THREAD

**Issue by JamesGuthrie** [JukkaL/mypy#656]
The [tutorial][1] and [wiki][2] contain a number of references to `typevar` as opposed to the newer `TypeVar`, which is slightly confusing.

[1]: http://mypy-lang.org/tutorial.html
[2]: http://www.mypy-lang.org/wiki/PythonCompatibleSyntax

**Comment by JukkaL** [comment]
Thanks for reporting this!

This tutorial was really stale and no longer relevant... Also, the linked wiki page is obsolete. Fixed the links (plus a few additional links that I found) and removed stale content.
