### ISSUE TITLE
Support assigning ellipsis with type hint

### ISSUE THREAD

**Issue by JamesGuthrie** [JukkaL/mypy#675]
The old convention for type hinted variable definition:

    a = Undefined(int)

has been superseded by the [new convention](https://github.com/ambv/typehinting/issues/81#issuecomment-98580602):

    a = ...  # type: int

Mypy's type checker warns against this assignment with the message: `Incompatible types in assignment (expression has type "ellipsis", variable has type "int")`

**Comment by JukkaL** [comment]
Note that the ellipsis syntax should on be valid in stubs. To implement this, we need to detect whether a file is a stub, based on the extension. 

This issue depends on https://github.com/JukkaL/mypy/issues/623 and https://github.com/JukkaL/mypy/issues/650.
