### ISSUE TITLE
Remove inheritance of concrete types

### ISSUE THREAD

**Issue by JamesGuthrie** [JukkaL/mypy#688]
Since https://github.com/ambv/typehinting/commit/5cbb342afed9784846b6bbf4436aea70b5b56532, certain classes within mypy are no longer valid, for instance the [SymbolTable](https://github.com/JukkaL/mypy/blob/master/mypy/nodes.py#L1616) inherits Dict[str, SymbolTableNode].

**Comment by JukkaL** [comment]
Thanks for reporting this! I don't think that this is intentional. I created an issue in typehinting (see the link above).

**Comment by JamesGuthrie** [comment]
Looks like this has been addressed in typehinting
