### ISSUE TITLE
Is there a way to type-alias a generic type?

### ISSUE THREAD

**Issue by ddzville** [JukkaL/mypy#697]
Can I write a generic type-aliase so that:

```MyBundle[t]``` is exactly equivalent to ```Tuple[List[t], t, List[t]]```

**Comment by spkersten** [comment]
This will be possible in the future, but is not yet supported by mypy. See #606 and the ambv/typehinting issue it refers to.

**Comment by JukkaL** [comment]
I chatted about this with Guido and he's only planning to support simple aliases like this:

```
X = Tuple[T, int]

# Now X[str] is equivalent to Tuple[str, int]
```

Cases where the type variable is deeply nested in the alias target probably won't be supported. If you care about this, you should probably ask about it on the ambv/typehinting issue. I actually promised to add this feature to PEP 484, but I haven't yet done it...
