### ISSUE TITLE
Overwriting sys.excepthook

### ISSUE THREAD

**Issue by ze-phyr-us** [JukkaL/mypy#707]
How do I set my own excepthook? mypy complains about "Invalid assignment target":

```
$ cat hook.py
from types import TracebackType
import sys


def excepthook(type_: type, value: BaseException, tb: TracebackType) -> None:
	sys.__excepthook__(type_, value, tb)

sys.excepthook = excepthook
```

```
$ mypy hook.py
hook.py, line 8: Invalid assignment target
```

(Python 3.4, mypy from master)

**Comment by spkersten** [comment]
mypy (currently?) doesn't support redefining a symbol in a module like that.

You could try this instead:

```python
import sys

setattr(sys, 'excepthook', None)
```

**Comment by ze-phyr-us** [comment]
Oh, okay. I went with `sys.excepthook = excepthook # type: ignore`, seems less invasive this way.

**Comment by JukkaL** [comment]
The stub for `sys` (`stubs/3.2/sys.pyi`) should define `excepthook` as a variable with a callable type instead of a function (also, mypy should support assigning to functions, but that's a separate issue).

**Comment by gvanrossum** [comment]
Can't repro any more.
