### ISSUE TITLE
stubgen UnicodeDecodeError on files containing `coding` magic comment and extended characters

### ISSUE THREAD

**Issue by dmwyatt** [JukkaL/mypy#709]
On this file:

https://github.com/dateutil/dateutil/blob/master/dateutil/parser.py

I get: 

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 1313: invalid continuation byte`

I'm not sure of the best way forward on fixing this issue.

**Comment by JukkaL** [comment]
Ah, this seems like a stubgen bug. Thanks for reporting this! I've been very busy for the past several weeks but I'll try to look at this in more detail once I'm back home next week.

However, you may try adding a `'rb'` option to the `open()` call below and see if it fixes the problem:

```
 File "/Users/jukka/random/mypy/mypy/stubgen.py", line 47, in generate_stub
    source = open(path).read()
```

**Comment by darjus** [comment]
Hey Jukka, what do you think of the pull request i submitted for this issue?
Thanks!
