### ISSUE TITLE
List concat with different types causes error

### ISSUE THREAD

**Issue by noisecapella** [JukkaL/mypy#720]
When I run mypy on this code:

    from typing import List, Any

    def f(a: List[int], b: List[str]):
        return a+b

    f([1,2,3], ["3","4","5"])

I get this error:
    /home/georgeatmit/type1.py: note: In function "f":
    /home/georgeatmit/type1.py:3: error: Unsupported operand types for + ("list" and List[str])

Is combining lists of different types supported at the moment?

**Comment by gvanrossum** [comment]
I think it's fine to get an error for this -- it's more likely to be a
programming mistake than intentional. Maybe you can use `cast()` to remove
the warning if this is really what you want?

**Comment by noisecapella** [comment]
I agree that this looks like a programming mistake, I was wondering about the general rule of combining collections with different types in Python's type hinting syntax, and a bit confused with the error message, why `List[int]` shows up as `"list"` but `List[str]` is represented correctly. I'll do some investigating and file another issue if I find anything.

**Comment by graingert** [comment]
```python
from typing import List, Any

def f(a: List[int], b: List[str]) -> List[Union[str, int]]:
    return a+b

f([1,2,3], ["3","4","5"])
```

should be totally valid.

**Comment by graingert** [comment]
```python
_T = TypeVar('_T')
_U = TypeVar('_U')

def list_add(a: Iterable[_T], b: Iterable[_U]) -> Iterable[Union[_T, _U]]:
    items: Iterable[Iterable[Union[_T, _U]] = [a, b]
    return itertools.chain.from_iterable(items)

f: Callable[[List[int], List[str]], List[Union[str, int]] = list_add
```

should do this without cast.

**Comment by Randl** [comment]
I agree that this should be re-opened

**Comment by kanakisaki** [comment]
Any updates? It's still very relevant...
Just faced the same situation, and I don't actually want to create workarounds every time...

**Comment by JelleZijlstra** [comment]
The original example typechecks for me now, likely thanks to python/typeshed#8293. If you have a different problem, please open a new issue.
