### ISSUE TITLE
Infinite loop when processing certain packages.

### ISSUE THREAD

**Issue by public** [JukkaL/mypy#725]
I discovered this when trying to run MyPy on https://github.com/pyca/cryptography

`mypy -m cryptography` hangs forever at 100% CPU. Via PDB and strace I found that it was processing the same files over and over and never getting anywhere.

I have reduced this to a fairly simple test case.

Create a package like

`LOOP/__init__.py`
```
from LOOP.SUBLOOP import LOOPVAR
```

`LOOP/SUBLOOP.py`
```
LOOPVAR = "Loops!"
```

Run `mypy -m LOOP`. It will never complete.

I have tested this on Python 3.4.0 with MyPy 0.2.0 on Ubuntu 14.04.

I'm currently at EuroPython if anyone who knows about this stuff would like to pair on fixing it or just getting a reproduction working :)

**Comment by o11c** [comment]
Although import logic *is* screwed up, `mypy -m LOOP` isn't valid python code if LOOP is a package unless you have a `__main__.py`, and additionally it is never possible to import from the main module since it would be imported twice.

If you want to tell mypy to test a single module, try using my fork (branch `driver`, PR failing due to *other* import bugs) and running `mypy -c 'import LOOP'`.

**Comment by o11c** [comment]
Also, bugs against Mypy 0.2.0 are not particularly useful, use git.

**Comment by public** [comment]
You get the same behaviour with a `__main__.py` present. I also get the exact same behaviour using the latest MyPy on git.

**Comment by o11c** [comment]
`find_module` in `mypy/build.py` should be changed to add a parameter to say whether it should return `package/__init__.py` or `package/__main__.py`.

**Comment by JukkaL** [comment]
Thanks for reporting this! This looks similar to #647, but I can't say whether it's the same issue yet.

**Comment by JukkaL** [comment]
@o11c I think that it's useful to allow using `mypy -m` even if there is no `__main__.py`, as we don't actually run the module but just type check it. But still, if there is `__main__.py` it should take precedence over `__init__.py`.

**Comment by JukkaL** [comment]
The fix to #647 has fixed the original issue (infinite loop).
