### ISSUE TITLE
TypeJoinVisitor doesn't support visit_overloaded()

### ISSUE THREAD

**Issue by JamesGuthrie** [JukkaL/mypy#729]
I'm still experimenting with #638, I have made some progress, but seem to have stumbled across a mypy bug with my test case. The type checker fails because the type `Overloaded` is not handled by the TypeJoinVisitor. How should the Overloaded type be joined with other types?

**Comment by JukkaL** [comment]
Hmm... I started thinking about this and it's about as easy (or difficult) to implement this as to specify how it would work. I hope to have an implementation ready in a couple of days, but this is actually pretty subtle if we want to deal correctly with `Any` types, etc.

**Comment by JukkaL** [comment]
Finally got around to fixing this. Please let me know if the fix works for you.
