### ISSUE TITLE
Forward references to nested classes

### ISSUE THREAD

**Issue by dominique-unruh** [JukkaL/mypy#744]
Forward references to nested classes do not seem to be possible, see the example below (verified with mypy 0.2 from pypi).

```python
class A():
    def b(self, x:'B') -> None: pass # works
    def c(self, x:'B.C') -> None: pass # Error: Name 'B.C' is not defined

class B():
    class C(): 
        pass
```

In this case, of course, the problem can be circumvented by reordering the definitions. But in the case of circular references, reordering becomes impossible. (For example, PyQt contains a lot of references to subclasses, making it very hard to generate stubs for PyQt.)

**Comment by JukkaL** [comment]
Thanks for reporting this! The bug exists on github master as well. 

I'm pretty sure that it's because the first pass of semantics doesn't look inside classes. This should not be too difficult to fix. I marked this as priority as this blocks some third party library stubs.

**Comment by JukkaL** [comment]
This is now fixed in the `hack` branch.
