### ISSUE TITLE
Run mypy parser against a lot of Python 2 code report issues

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#757]

**Comment by o11c** [comment]
The parser part I'm handling, it's analysis and stubs that are the open-ended task.

**Comment by JukkaL** [comment]
We are currently working on improving the Python 2 stubs and for that the current parser is not good enough. So we'll hack the current parser to work a little better for Python 2 code so that we can use the stub generator with more modules. These parser changes will be replaced once we have the new parser in, but at least we get some useful test cases out of this (and stubs!).

**Comment by JukkaL** [comment]
Or do you think that the new parser is good enough already?

**Comment by o11c** [comment]
I'm still in the process of writing it, but I've resolved all the major design problems so it's just a matter of writing out all the parse_* methods.

What I *haven't* done is looked into how much effort it is to rebase the `driver` branch, which needs to be merged before `syntax`.

**Comment by JukkaL** [comment]
I've done a few small updates to the current parser so that it can parse more Python 2 code, but there are still some remaining issues.

**Comment by JukkaL** [comment]
I think we've reported at least almost all of the major Python 2 parsing issues in the current parser, so I'm closing this now.
