### ISSUE TITLE
Support tuples within function headers in Python 2 

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#785]
Support functions like these in Python 2 (only):

```python
def f(x, (y, z)): ...
```

**Comment by JukkaL** [comment]
This is  quite a lot of work to implement while this is a rarely used feature. Probably better to postpone this for now.

**Comment by o11c** [comment]
Basically a duplicate of #746

My `syntax` branch will contain the parser part, but not lower to `mypy.nodes` classes. But most likely the second half is simple since `(y, z)` is already a valid assignment target.

**Comment by o11c** [comment]
Note that if `coding: mypy` is used, I will support `def f(x: X, (y: Y, z: Z)) -> W: ...` but *not* `def f(x: X, (y, z): Tuple[Y, Z]) -> W: ...`.

This is because I stole this part of the merged grammar from `lib2to3`.

**Comment by JukkaL** [comment]
Closing as duplicate of #746.
