### ISSUE TITLE
Tracker issue for Third Party stubs

### ISSUE THREAD

**Issue by o11c** [JukkaL/mypy#792]
This bug exists solely as a place to centralize discussion regarding third-party stubs right now.

My pending `driver` PR moves the python3 third-party stubs (currently `requests` and `docutils`) to `stubs/third-party`.

I discovered that it is a nontrivial amount of work to separate out the standard vs third-party stubs after the fact, so if any are generated during whatever this "hack" thing should be clearly marked.

**Comment by JukkaL** [comment]
We are going to add a file with a list of all third-party stubs. We are now having a hackathon style thing where we focus on improving Python 2 support.

(And I'll try to dedicate some time to look at your PR soon so that it doesn't get too hard to merge. Sorry about the delay.)
