### ISSUE TITLE
sys.version_info needs to support __getitem__.

### ISSUE THREAD

**Issue by kylec1** [JukkaL/mypy#812]
In particular, some generated code uses it to select between Python 2 and 3 with `sys.version_info[0]`.

**Comment by o11c** [comment]
I have that in my fork I think

**Comment by o11c** [comment]
https://github.com/o11c/mypy/commit/2cfd3dac901de52ed1cc82e88b9cb7ff7c45c674#diff-63a9b4609f3df3266bc8eac56507e2d5L101

**Comment by o11c** [comment]
I was having difficulties with `NamedTuple` at the time, not sure if that is a viable alternative or not.

**Comment by JukkaL** [comment]
Seems like `NamedTuple` could work, but the concrete type doesn't seem like a named tuple, at least in Python 2.

**Comment by o11c** [comment]
I was only recently aware of the `_fields` thing being the defining aspect of the `namedtuple` protocol. Previously I assumed that any subclass of `tuple` that used readonly property-like attributes counted.

You're right that it doesn't match the protocol then.

Though it has some curious `n_fields`, `n_sequence_fields`, `n_unnamed_fields` (at least in python3).
