### ISSUE TITLE
mypy confused by defaultdict(list)

### ISSUE THREAD

**Issue by MichalPokorny** [JukkaL/mypy#815]
Source:
```
from collections import defaultdict
x = defaultdict(list)
```

Error:
```
test.py:2: error: Argument 1 to "defaultdict" has incompatible type List[_T]; expected Callable[[], List[_T]]
test.py:2: error: Need type annotation for variable
```

**Comment by o11c** [comment]
What happens if you add `# type: defaultdict[List[int]]` or whatever the actual type of the list is?

**Comment by MichalPokorny** [comment]
`x = defaultdict(list) # type: defaultdict[str, List[str]]` ==> `test.py:2: error: Argument 1 to "defaultdict" has incompatible type List[_T]; expected Callable[[], List[str]]`

**Comment by MichalPokorny** [comment]
Also, this is an issue on the `hack` branch -- master might or might not have this issue.

**Comment by JukkaL** [comment]
Also happens on master. Here is a self-contained repro suitable for a unit test:

```
from typing import Generic, Callable, TypeVar

T = TypeVar('T')

class C(Generic[T]):
    def __init__(self, x: Callable[[], T]) -> None: ...

class D(Generic[T]): pass

a = C(D)
b = C(D) # type: C[D[str]]
```

**Comment by gvanrossum** [comment]
How hard would this be? The majority of uses of defaultdict that I see have one of the builtins `set` or `list` as argument. (Also the error message seems wrong -- the argument is not a value of type `List[_T]`, it's a class representing that type.)

**Comment by JukkaL** [comment]
I haven't look into this yet but my guess would be that I could fix this pretty quickly.

**Comment by gvanrossum** [comment]
One quick hack would be to just add another overload to `collections.pyi`:
```
    @overload
    def __init__(self, default_factory: type) -> None: ...
```
But this feels wrong -- it should just know that these types are callables of 0 arguments.

**Comment by gvanrossum** [comment]
If you decide to fix this in typeshed, also note that two of the overloads
of `defaultdict.__init__` are wrong -- it does *not* take a map or iterable
first parameter (those must be the second). Also the `default_factory`
parameter should be `Optional`. Keyword args are treated like dict's
keyword args.

On Sun, Dec 13, 2015 at 8:49 PM, Jukka Lehtosalo <notifications@github.com>
wrote:

> I haven't look into this yet but my guess would be that I could fix this
> pretty quickly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JukkaL/mypy/issues/815#issuecomment-164342249>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by JukkaL** [comment]
I'll give this a try tomorrow or Tuesday.
