### ISSUE TITLE
Multiple del not properly parsed

### ISSUE THREAD

**Issue by MichalPokorny** [JukkaL/mypy#833]
```
a = 1
b = 2
del a, b
```
Gives: `error: Invalid delete target`

**Comment by pgunn** [comment]
@JukkaL FYI, a variant syntax that's Python-legal still doesn't work under mypy (although maybe it's better to rewrite offending code):

`del([a, b])`

**Comment by brandtbucher** [comment]
I see the issue, and I'll fix it to properly fit the grammar when I get a free minute. Nice catch!
