### ISSUE TITLE
Allow mypy to be run against a directory recursively

### ISSUE THREAD

**Issue by kylec1** [JukkaL/mypy#838]
It'd be useful to be able to run mypy on a whole project (or a subset of one) by just pointing it at a directory, and that can probably be done more efficiently than checking each module or file individually, as type information from dependencies could be shared.

**Comment by JukkaL** [comment]
Yeah, this would be pretty useful.

**Comment by o11c** [comment]
On my `driver` branch you can badly work around this with `mypy -c 'import foo, foo.bar, foo.baz'` (listing all). It shouldn't be hard to add a new flag that generates a `-c`.

But (and this is critical) note that this will allow certain import-order-related bugs to go undiagnosed. Mypy had several bugs in this regard, this why my `driver` PR typechecks each module individually.

**Comment by alunduil** [comment]
Is this being deprecated in favour of #935 ?

**Comment by JukkaL** [comment]
#935 covers a superset of this issue, so this is no longer relevant. We may still support running against a whole directory, but we've discussed that in the context of #935.

**Comment by gvanrossum** [comment]
(The fix for #935 also adds support for this.)
