### ISSUE TITLE
Type check error with overloaded function

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#854]
```
from typing import overload

@overload
def f(x: int) -> int: pass
@overload
def f(x: float) -> float: pass

f(1 - .1) # E: Argument 1 to "f" has incompatible type "float"; expected "int"
```

Probably picks the wrong overload item for some reason.

This seems like the same issue:

```
[1 - .1]  # error
```

**Comment by kirbyfan64** [comment]
I thought overloading was only valid in stubs now?

**Comment by JukkaL** [comment]
Yeah, the example isn't actually valid code (think of it as `f` being defined in a stub and the call is in a `.py` file). Mypy currently doesn't actually verify this right now, so you can use the example as a mypy test case, but the code can't be run.
