### ISSUE TITLE
mypy can't find configparser module

### ISSUE THREAD

**Issue by mgrinder** [JukkaL/mypy#871]
When I run mypy against a file that uses configparser, I get an error:

cfg.py, line 1: No module named 'configparser'

This is on python 3.4.

**Comment by JukkaL** [comment]
Mypy needs library stub files to type check code using them. You can generally generate (dynamically typed) stub files by using the bundled stub generator:

```
$ python3 -m mypy.stubgen configparser
```

Then copy `out/configparse.pyi` to somewhere where mypy can find it (either same directory as your program or a directory in `MYPYPATH`).

The generated stub files aren't always perfect, but stubgen usually does a pretty good job. If the stub file seems good, feel free to contribute it to the mypy github repo.

**Comment by mgrinder** [comment]
Thanks. I should have read the docs more carefully. I had assumed that the standard libraries already had stubs.

**Comment by JukkaL** [comment]
Yeah, it was a reasonable expectation but currently many stubs are still missing. Maybe I should just generate stubs for all standard library modules even if some of them might be a little broken. We'd then fix issues in stubs after the fact as people would report them. I assume that at least 90% of the modules would get useful stubs this way.
