### ISSUE TITLE
Mypy installation fails with virtualenv

### ISSUE THREAD

**Issue by uetoyo** [JukkaL/mypy#878]
When I install *mypy* as global package -- everything is ok, but when I try to install it under a *virtualenv*  folder, it fails with `ImportError`.
```
import importlib._bootstrap_external
ImportError: No module named 'importlib._bootstrap_external'
```

Python3.5/Win7

**Comment by iljabauer** [comment]
Hi,

are you sure you installed mypy with

    pip install mypy-lang

and not

    pip install mypy

?

Unfortunately there is a package called mypy on pypi with no association to this project.

**Comment by uetoyo** [comment]
I am sure that I installed it as `pip install mypy-lang`.

**Comment by gvanrossum** [comment]
This may not be something the mypy folks can help you with -- it seems to be a venv-related issue. Does the same problem happen when you try to install something else using pip in that venv? What if you create a fresh venv? Does it work when you use Python 3.4 instead?

**Comment by uetoyo** [comment]
I'v created the fresh venv and it works. I cannot reproduce the problem, so it seems that it was virtualenv issue. --> `Successfully installed mypy-lang-0.2.0` .) Thanks a lot @ iljabauer, @gvanrossum !
