### ISSUE TITLE
MyPy on Django

### ISSUE THREAD

**Issue by chintanop** [JukkaL/mypy#881]
I have been trying to get Django 1.8 (or 1.9) + python3 working with mypy

If I import any Django model, I get this - https://gist.github.com/chintanop/e6145e34a1f0293a6faa

Works fine if I # type: ignore the imports but then I loose type checking for Django ORM classes.

**Comment by o11c** [comment]
It looks like you're giving a real copy of `importlib` a higher priority than the stubs. That's not going to work; make sure the stubs have the highest priority.

**Comment by chintanop** [comment]
:+1: 
Great! worked - didn't realize the concept of "stubs". Will be contributing stubs for Django.
