### ISSUE TITLE
Make it possible to install typing for Python 2

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#920]
We should have a way of installing `typing` on Python 2. There are at least two alternatives:

1. Add something like `setup_typing_py2.py` that installs `typing` (only on Python 2). Not sure what the script should be called, but we should probably have a fairly descriptive name to make clear that this doesn't actually install mypy. Maybe this should be available via `pip install mypy-typing` or something. Alternatively, make this work on Python 3 as well.
2. Use a separate repo for `typing` and install it using `pip install typing` or so (at least for Python 2, but maybe also for pre-3.5 Python 3). This makes it more difficult to change `typing`, so we may want to postpone this until the implementation is stable and reasonable complete. We need to figure out who actually owns typing on pip now (I remember that there was a discussion about this a while back but I was then in the middle of moving my family to a different continent and was distracted.)

The long term goal is 2, but we may want to start with 1 until we have a better understanding of how things should work.

See also the original issue from where this came from: https://github.com/JukkaL/mypy/issues/917

**Comment by gvanrossum** [comment]
We're almost there with the typing repo. I've sent a PR that updates that repo to the current state from mypy: https://github.com/JukkaL/typing/pull/47

**Comment by vlasovskikh** [comment]
@gvanrossum I ported ambv/typehinting to Python 2.7 a month ago (https://github.com/ambv/typehinting/issues/160) and uploaded typing 3.5.0.1 to PyPI.

**Comment by gvanrossum** [comment]
Ah, much better. I'll use that. Jukka: maybe you should just delete your typing repo then?

**Comment by JukkaL** [comment]
I updated my typing repo to have a prominent pointer to @vlasovskikh's version at the top of the readme.
