### ISSUE TITLE
Add a code of conduct for mypy?

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#924]
I had to block a user who has behaving disrespectfully on the mypy repo. I really hate doing this and I'd like us to be able to prevent this from happening again. Having a code of conduct that we can point people to might improve things. We can either borrow a code of conduct from another project or come up with something simple ourselves. Here the kinds of things that we might include (all no-brainers, I assume, but let me know if you disagree):

* Respect others and behave in a civil manner.
* Understand that almost everybody is working on this project on their spare time and have other commitments such as work, family, friends and hobbies. You can't expect volunteers to always respond quickly or to be able to dedicate a lot of time working on your PRs (but we try to do our best).
* Don't complain about management or advocate forking mypy in comments of unrelated issues. Feel free to open an issue to discuss whatever aspect that you don't like, but adding noise to comments just makes things inconvenient for everybody.
* Listen to what core contributors say and try to understand their concerns. Respect their time.

Some context in #915 , but this had been going on for a while.

I believe that the issue originated from me being slow to respond to pull requests while I was helping my family to move from the US to Europe and looking for a new place to live in, and while I was visiting them for three weeks (and didn't have time to work on mypy). A potential improvement would be to have more core contributors who can review PRs. If anybody in interested in becoming a core contributor, please let me know.

**Comment by kirbyfan64** [comment]
Is there a need for an explicit CoC, other than "if you act like an idiot, you will be blocked?" I mean, the end result is the same...

**Comment by gvanrossum** [comment]
I recommend a 24 hour coll down period before continuing this discussion.

**Comment by kirbyfan64** [comment]
@gvanrossum s/coll/cool/

**Comment by kirbyfan64** [comment]
Actually, maybe you can just use [Python's CoC](https://www.python.org/psf/codeofconduct/)? I mean, since Mypy is for Python, and the `typing` module is now part of Python, and all...

**Comment by gnprice** [comment]
I like @kirbyfan64's suggestion. I'm not sure I'd looked at the Python CoC before, but it's nicely written and I think it covers the issues @JukkaL has in mind. If we all agree that it's suitable, that will save us the work of wordsmithing a new one, and it will also have a nice consistency to it.

**Comment by JukkaL** [comment]
Okay, sounds good -- I added a link to the Python CoC: http://www.mypy-lang.org/wiki/DeveloperGuides

**Comment by brettcannon** [comment]
A really good way to get the CoC in front of developers is to create a `CONTRIBUTING` file and link to it from there. That way all PRs and issues will have a little banner linking to the `CONTRIBUTING` file.

**Comment by gnprice** [comment]
Thanks, @brettcannon -- I hadn't known about that GitHub feature! Just filed a new issue for that, #1265.
