### ISSUE TITLE
Show the total number of test cases run

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#951]
`runtests.py` should display the number of tests cases run. Rationale:

* This used to (mostly) work before the switch to `runtests.py`.
* If you use test case filtering, you get an indication of whether your filter hit anything.
* This provides an extra incentive to add tests, as the effects will be visible in the test count.
* If some change accidentally disables a large number test cases, this will be obvious.

**Comment by jhance** [comment]
I don't think currently theres any mechanism for the collection of myunit tests to tell the driver how many tests they ran. We could parse it from stdout, though.

**Comment by JukkaL** [comment]
I'm going to update `waiter.py` to parse stdout, as this seems like the easiest thing to do and it'll be robust enough. It's going to make `waiter.py` somewhat coupled with `myunit`, but that's okay.

**Comment by jhance** [comment]
I think thats fine. `waiter.py` isn't really part of `mypy` anyway (we should probably put it in a different location - we shouldn't be exporting this as a module in the `mypy` package)

**Comment by JukkaL** [comment]
Closed by https://github.com/JukkaL/mypy/commit/d07c46087b9139f271b0cb57fd957f12397c91cb. This still doesn't report ignored test cases but it's better now.
