### ISSUE TITLE
Mypy does not recognize that raise exits from function

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#956]
Mypy complains about this:

```
from typing import Union

def f(x: Union[int, str]) -> None:
    if not isinstance(x, int):
        raise RuntimeError()
    print(x + 1)  # Can't add Union[int, str] and int
```

However, this works:

```
from typing import Union

def f(x: Union[int, str]) -> None:
    if not isinstance(x, int):
        raise RuntimeError   # Only difference!
    print(x + 1)  # Now okay!
```

Perhaps the slightly different `raise` statement causes a difference in type inference, or maybe this is something more complex?

**Comment by JukkaL** [comment]
This also misbehaves:

```
from typing import Union

def f(x: Union[int, str]) -> None:
    if not isinstance(x, int):
        return foo()
    x()

def foo(): pass
```

Maybe it's something with call expression that confuses things.

**Comment by jhance** [comment]
This is odd.

I believe that the key is the `self.breaking_out`, but `raise` sets that to `True`.

**Comment by JukkaL** [comment]
#957 fixed this (thanks @ecprice !).
