### ISSUE TITLE
Test runner can hang if there is a lot of output

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#961]
In `mypy/waiter.py` we wait until a task ends before reading stdout and stderr, which are pointing to a pipe. However, if a test generates a lot of output writing to the pipe will hang, as it can only buffer a fixed amount of data (http://unix.stackexchange.com/questions/11946/how-big-is-the-pipe-buffer). 

There are a number of things we can do to fix this, such as:

1. Have a thread that continually reads from the pipe and adds any written data to an explicit internal buffer.
2. Redirect output to a file and read it from the file after task exit. This is probably cleaner than the above and easier to implement.

**Comment by jhance** [comment]
What about using a `BytesIO` or `StringIO` as an intermediate buffer?

https://docs.python.org/3/library/io.html

**Comment by JukkaL** [comment]
Oh yes, I had forgotten about it. We should use it if it works with arbitrary-sized output.

**Comment by jhance** [comment]
I was kind of hoping you would know if they did; the documentation was not very useful for me

**Comment by JukkaL** [comment]
Actually, I didn't remember this correctly. There was some discussion of supporting `BytesIO` as an argument to `communicate` but apparently that didn't actually get in. `BytesIO` as output destination doesn't seem to work. I think that redirecting to a file is still the easiest thing to do in this use case.

**Comment by jhance** [comment]
But shouldn't a file object and a BytesIO be the transparently the same?

**Comment by JukkaL** [comment]
I'm pretty sure that `subprocess` expects a file object that supports `fileno()`, and `BytesIO` doesn't provide that (it raises `UnsupportedOperation`).
