### ISSUE TITLE
line 1: Could not find builtins—running in venv

### ISSUE THREAD

**Issue by alunduil** [JukkaL/mypy#967]
When trying to run `mypy -m module` inside of a venv I'm getting this error:

```
module/__init__.py, line 1: Could not find builtins
```

The module's definition is:

```
# Preamble Comment
```

The venv has a python version of 3.4.3.

**Comment by JukkaL** [comment]
Thanks for reporting this! Mypy needs better tests around installation -- it seems that each time something around it is touched, something gets broken.

**Comment by alunduil** [comment]
@JukkaL no worries.  If it helps I ran into this while using mypy during a circle CI run.

**Comment by JukkaL** [comment]
I can't reproduce this -- I probably don't have the same configuration. 

Some questions that may help me diagnose this:

1. Where is mypy installed (and how)? Is it in the venv?
2. What do you have installed in your venv?
3. Where does `module/__init__.py` live relative to the venv?
4. Do you have `MYPYPATH` defined?
5. Have you tried the latest github master?
6. Which OS are you using?

**Comment by alunduil** [comment]
Hmm, I'm not getting that problem anymore but now I can't get it to parse my files correctly in that environment.  Using ``--use-python-path`` I get parse errors on valid python.  I can compose a relevant snippet if necessary but maybe it's just something I'm not including?  I'm working with a tornado application (including futures and coroutine generators).  Are there any known issues with that environment that I'm overlooking?

To answer your above questions (in case the issue crops back up):

1. mypy is installed into the venv via circle's magic process using their venv installed pip version
2. pip freeze:

alabaster==0.7.6
application-manager==1.0.0.dev0
astroid==1.4.1
attrdict==2.0.0
Babel==2.1.1
backports-abc==0.4
boto==2.38.0
boto3==1.2.2
botocore==1.3.9
colorama==0.3.3
coverage==4.0.3
crumbs==2.1.0
docutils==0.12
hypothesis==1.15.0
Jinja2==2.8
jmespath==0.9.0
lazy-object-proxy==1.2.1
logilab-common==1.1.0
MarkupSafe==0.23
mypy-lang==0.2.0
nose==1.3.7
omnicon==1.0.0.dev0
Pygments==2.0.2
pylint==1.5.0
python-dateutil==2.4.2
pytz==2015.7
retcd==1.0.0.dev0
six==1.10.0
snowballstemmer==1.2.0
Sphinx==1.3.2
sphinx-rtd-theme==0.1.9
torment==3.0.1
tornado==4.3
wrapt==1.10.5

3. I can't find module/__init__.py at all.  Where should it be installed?
4. MYPYPATH is not defined.
5. I have not tried master (this version works on my local box just fine).
6. os-release:

```
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"
```

**Comment by gvanrossum** [comment]
Are you using the mypy from the github repo? The PyPI version is pretty out
of date.

--Guido (mobile)

**Comment by alunduil** [comment]
I have not but I'll give that a try and see if it rectifies the problems.  Thanks!
