### ISSUE TITLE
ImportError: cannot import name 'Undefined'

### ISSUE THREAD

**Issue by halbtuerke** [JukkaL/mypy#975]
I just installed mypy via `pip install mypy-lang` and when I try to use it the following error message occurs:

```
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 14, in <module>
    from mypy import build
  File "/usr/local/lib/python3.5/site-packages/mypy/build.py", line 19, in <module>
    from typing import Undefined, Dict, List, Tuple, cast, Set, Union
ImportError: cannot import name 'Undefined'
```
The shebang of `/usr/local/bin/mypy` is `#!/usr/local/opt/python3/bin/python3.5`.

I have Python 3.5 installed via Homebrew and I'm running OS X 10.11.1.

Please let me know if you need any further information.

**Comment by gvanrossum** [comment]
`Undefined` was removed from PEP 484 and mypy no longer supports it.

**Comment by halbtuerke** [comment]
So what can I do to actually use mypy?

**Comment by kirbyfan64** [comment]
@halbtuerke Can you get it from Git?

```
$ pip install git+git://github.com/JukkaL/mypy.git
```

**Comment by halbtuerke** [comment]
Installing it directly from source works Thanks.

**Comment by Daenyth** [comment]
When do you plan to update pypi with a version that works for 3.5?

**Comment by gvanrossum** [comment]
Probably not for a while -- we're just changing things too fast to be
release-worthy. Sorry.

--Guido (mobile)
