### ISSUE TITLE
Installing On Windows - ImportError: cannot import name 'Undefined'

### ISSUE THREAD

**Issue by jakeonaut** [JukkaL/mypy#980]
I'm installing on Windows 7 64bit. Trying both "python3 -m pip install mypy-lang" and installing directly by running "python setup.py install" for both release versions of the project seem to work. 

However, once I'm sure all the paths are set up, running mypy any_file.py results in the following error:

D:\cake\code\python>mypy mypy_test.py
Traceback (most recent call last):
  File "C:\Python35\Scripts\mypy", line 14, in <module>
    from mypy import build
  File "C:\Python35\lib\site-packages\mypy\build.py", line 19, in <module>
    from typing import Undefined, Dict, List, Tuple, cast, Set, Union
ImportError: cannot import name 'Undefined'

As such, I cannot properly use the project under Windows currently :(. Not sure if I'm missing any necessary steps here.

**Comment by kirbyfan64** [comment]
Try:

```
$ pip install git+https://github.com/JukkaL/mypy.git
```

**Comment by jakeonaut** [comment]
Running `$ pip install git+https://github.com/JukkaL/mypy.git` failed with the following error:

```
D:\cake\code\python\dive3>pip install git+https://github.com/JukkaL/mypy.git
Downloading/unpacking git+https://github.com/JukkaL/mypy.git
  Cloning https://github.com/JukkaL/mypy.git to c:\users\jake\appdata\local\temp
\pip-fkpyma-build
  Running setup.py (path:c:\users\jake\appdata\local\temp\pip-fkpyma-build\setup
.py) egg_info for package from git+https://github.com/JukkaL/mypy.git
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "c:\users\jake\appdata\local\temp\pip-fkpyma-build\setup.py", line 10
, in <module>
        from mypy import git
      File "mypy\git.py", line 10
        def is_git_repo(dir: str) -> bool:
                           ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "c:\users\jake\appdata\local\temp\pip-fkpyma-build\setup.py", line 10, in
 <module>

    from mypy import git

  File "mypy\git.py", line 10

    def is_git_repo(dir: str) -> bool:

                       ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in c:\users\jake\appda
ta\local\temp\pip-fkpyma-build
Storing debug log for failure in C:\Users\jake\pip\pip.log
```

However, running `$ python -m pip install git+https://github.com/JukkaL/mypy.git` seemed to install successfully! And trying to run mypy on a python file to test resulted in it working with no weird error messages!

Thank you very much :)

**Comment by kirbyfan64** [comment]
FYI, this is just because the version of Mypy on PyPI uses a custom typing module, and Python 3.5 comes with a slightly different one. The `pip` error was probably just that your `pip` is for Python 2, not 3.

**Comment by jakeonaut** [comment]
You were right about the `pip` error. Thought I had modified the executable names for Python27 so they would not be executed from the console, but I had missed changing `pip.exe` to `_pip.exe`! Thanks again.
