### ISSUE TITLE
incorrect use of List constructor causes internal error

### ISSUE THREAD

**Issue by bcdarwin** [JukkaL/mypy#981]
mypy -c "l = [(1, True), (3, False)] # type: List[int, bool] # whoops ... should be List[Tuple[int, bool]]"

    Traceback (most recent call last):
    ....
        cb = infer_constraints(mapped.args[i], instance.args[i],
    IndexError: list index out of range

**Comment by JukkaL** [comment]
Thanks for reporting this! Mypy should definitely report this as an error instead of crash.

**Comment by JukkaL** [comment]
This seems to work now.

**Comment by kirbyfan64** [comment]
I think this was the same thing as #996.
