### ISSUE TITLE
Args to __new__ not recognized

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#982]
I have this code:
```
class C(object):
    def __new__(cls, foo=None):
        obj = object.__new__(cls)
        obj.foo = foo
        return obj

x = C(foo=12)
print(x.foo)
y = C(12)
```
This elicits an error complaining about the `foo` keyword to C, another about the `foo` attribute, and then one about the positional argument:
```
mypy_new.py:7: error: Unexpected keyword argument "foo" for "C"
mypy_new.py:8: error: "C" has no attribute "foo"
mypy_new.py:9: error: Too many arguments for "C"
```
This may be related to #794 -- feel free to close as a dupe if fixing that would automatically fix this. (There seem to be two separate issues here -- it doesn't turn the `__new__` signature into the class signature, and it doesn't believe attributes set by `__new__` become attributes of the object.)

**Comment by JukkaL** [comment]
#794 is a third issue -- classes should be able to override `__new__` with a different signature.

Attribute assignment can be worked around by defining attributes in the class body. Inferring attributes in `__new__` is hard to do in general, but we can probably support at least the most common idioms.

**Comment by JukkaL** [comment]
Marking as priority as this is a fundamental language feature that mypy doesn't support yet.

**Comment by JukkaL** [comment]
#794 actually covers an additional issue -- using `super()` with `__new__`.

**Comment by JukkaL** [comment]
Inferring signature from `__new__` now works in the most common cases. I'm going to create separate issues for remaining limitations:

* Inferring attributes from `__new__`
* Honoring return type of `__new__`

**Comment by JukkaL** [comment]
Closing this as the immediate issue is resolved, but see also the follow-up issues linked to above and #794 -- they are needed for more complete `__new__` support.
