### ISSUE TITLE
Don't guess at adding to MYPYPATH unless there's no __init__.py present

### ISSUE THREAD

**Issue by gnprice** [JukkaL/mypy#993]
Currently the CLI with `mypy foo/bar.py` follows the semantics of `python foo/bar.py` in adding `foo/` to the Python module search path.

This is the right thing to do when imitating `python` as a Python or Python-like interpreter, but in the context of type-checking some piece of a codebase it can get pretty confusing. In particular if there's a module inside `foo/` that has the same name as, say, a stdlib module, then we end up finding that when the stdlib module was intended. That's likely to produce super confusing error messages thereafter.

Instead, only add the target file's directory to the search path if there isn't an `__init__.py` present there. In this case, if the user's application was ever going to import that file, it must be by including that directory in the search path, so this isn't likely to cause confusion.

**Comment by gvanrossum** [comment]
Another possible idea: if we call `mypy some/path/to/a/file.py`, crawl up from the file until we find a directory that doesn't have an __init__.py.

**Comment by gvanrossum** [comment]
I've fixed this in PR #1035 (using the strategy from my last comment).
