### ISSUE TITLE
Incorrect number of type arguments causes internal error

### ISSUE THREAD

**Issue by bcdarwin** [JukkaL/mypy#996]
```
from typing import TypeVar

T = TypeVar('T')

class C(object):  # forgot to add type params here
    def __init__(self, t : T) -> None:
        self.t   = t

c = C(t = 3)  # type: C[int]  # this will crash
```

causes:

```
Traceback (most recent call last):
    ...
    cb = infer_constraints(mapped.args[i], instance.args[i],
IndexError: list index out of range
```

I guess this generalizes #981 and provides an additional example, here with an (accidentally) non-generic type (though the same happens if too few type arguments are supplied).  I'm not sure if it overlaps with #300.

**Comment by gvanrossum** [comment]
Hm... I'm seeing IndexError too, in a slightly different context (#991). Which version of mypy did you use? (The one from PyPI is way out of date -- #991 is with the current development HEAD.)

**Comment by kirbyfan64** [comment]
I think I found the issue! Hold on...

**Comment by bcdarwin** [comment]
It's a recent install from master, though I don't know how to (easily) find the commit.

**Comment by JukkaL** [comment]
I was able to repro this. Thanks for reporting the bug!

**Comment by kirbyfan64** [comment]
@JukkaL I fixed it already!
